### ISSUE TITLE
Adding i18n support

### ISSUE THREAD

**Issue by klh** [jedireza/drywall#151]
Perhaps add i18n.js should be easy to copy in from "generator-amdblah" ?

**Comment by klh** [comment]
just use i18next as mentioned above, it support both client side and server side.
and has a webtranslate gui as well ass string extraction, tried most of the libs out there and it is the easiest to implement, tons of generators aswell.\

http://i18next.com/
&
http://i18next.com/node/ (support for middleware etc.)


* support for variables 
* support for nesting 
* support for context 
* support for multiple plural forms  
* gettext support 
* sprintf supported 
* detect language 
* graceful translation lookup 
* jquery function 
* get string or object tree 
* get resourcefiles from server 
* resource caching in browser
* post missing resources to server 
* highly configurable 
* custom post processing 
* translation ui 

http://i18next.com/pages/ext_webtranslate.html
https://github.com/ckir/i18next-meteor/
https://github.com/mikefrey/i18ng
http://i18next.com/pages/ext_i18next-conv.html
https://github.com/auxilium/i18next-editor
https://github.com/rbeere/i18next-jade-express-sample

**Comment by jedireza** [comment]
Thanks for sharing @klh.

Would you be willing to post that in #268. This issue is closed and it may be better to share your idea in that active conversation.
