### ISSUE TITLE
User image. 

### ISSUE THREAD

**Issue by denzelwamburu** [jedireza/drywall#253]
Thanks for Drywall its really helpful. 
How can you add the option for user to upload a photo and after that it appears on the nav bar. Same for the logging in with other social accounts. The photo should appear in the nav bar.
How do i go around about that?

**Comment by jedireza** [comment]
I'm glad you're enjoying the project.

I think the easiest way would be to use the [Gravatar](https://en.gravatar.com/) MD5 of the user's email address. With that MD5 you can simply embed an image into the navbar. No extra work besides html markup.

See these instructions:
https://en.gravatar.com/site/implement/images/

```html
<img src="http://www.gravatar.com/avatar/9a4d8ddefcd21379425ece3cbda7a398 />
```

However, if you want a user to customize the image you'll need to create an upload form in account settings, store that image on disk etc...
