### ISSUE TITLE
Username and password combination not found or your account is inactive

### ISSUE THREAD

**Issue by metasection** [jedireza/drywall#256]
A tester registered as user@domain.com.  

They got the **"Username and password combination not found or your account is inactive"** error when trying to login sometime later.  

Turns out that they were logging in with User@domain.com.

Is the email address case sensitive?

*Unfortunately, I am away from my development machine and can't do a proper test on a clean Drywall install.*

**Comment by benpoole** [comment]
> Do you think it is better to make the fix in the login view or the passport "LocalStrategy"? I liked the idea of forcing lowercase for the username and email closer to the actual fineOne call.

I'd say the latter: you can forget about it then :) checking my code, I do the lowercase thing in the passport file for my project.
