### ISSUE TITLE
Admingroups vs Roles

### ISSUE THREAD

**Issue by bonyboy** [jedireza/drywall#257]
I'm trying to understand the difference between these 2 designations.  In my scenario I have 3 levels (User(R Access), Manager(R/W Access to User), and Admin(R/W Access to User and Manager).  From what I'm understand about Admingroups, I could do this by using the existing roles and just create Admingroups to lock things down with Permissions.

But what I like about the Roles way (and the affiliate example) is you seem to be creating a new schema for the Affiliate and I like the idea of keeping them away from the Admins as much as possible.  I would also be able to create an Affiliate view, which wouldn't be much different from the other views, but I would want certain things hidden.

Thanks!

**Comment by jedireza** [comment]
It will help if we get our terminology in line. You mentioned:

 > In my scenario I have 3 levels (User(R Access), Manager(R/W Access to User), and Admin(R/W Access to User and Manager).

But everyone is a User. :smiley: I don't mean to be lazy by quoting the wiki page so much, but I think these points help answer your question.

 > Why are roles separate from Users? For sanity really. Did you realize that both Admins and Accounts are indeed Users? Both of them need to login, both of them can forget their passwords and have them reset.

Reference: https://github.com/jedireza/drywall/wiki/Users%2C-Roles-%26-Groups

 > ### Thinking About Registration
 > The registration feature that comes with Drywall won't work for our new Affiliate role. As it shouldn't. Affiliates, like Admins, __should be unique enough roles that they deserve a unique creation flow.__ Remember that Admins can't register either. And that makes sense, we create other Admins in the backend, if we have permission to of course.

https://github.com/jedireza/drywall/wiki/Users%2C-Roles-%26-Groups#thinking-about-registration

 > ### Roles -vs- Groups
 > Roles should be unique enough to deserve their own schema. For example, if I'm a company, I could use my Admin schema to represent my employees. Then, I could add fields to my Admin schema for things like hourly rate, home address and benefits (other roles wouldn't have that type of data). Then I could use AdminGroups like departments (ex: Sales, Support, Manager). Now I can create permissions tied to AdminGroups and change the user experience based on that. Simply adding and removing a user's group memberships automatically changes their access permissions. Pretty sweet!
 > 
 > Can I use groups with Accounts? Sure. Your project might benefit by extending Accounts with an AccountGroup schema (and permissions). __For example, if I built a message board or wiki and I wanted some Accounts to moderate other Accounts or change site content... groups would be the perfect solution. It would be a huge overkill to create a new roll (and schema) for a Moderator, which is like an Account in every way, only differing by a permission.__

Reference: https://github.com/jedireza/drywall/wiki/Users%2C-Roles-%26-Groups#roles--vs--groups

---------------------------------

I hope this is helpful. If you're still looking for clarification would you try to articulate what your goals are in more detail?

**Comment by jedireza** [comment]
Closing for now.
