### ISSUE TITLE
Having trouble adding a new field to the user database.

### ISSUE THREAD

**Issue by fgruner** [jedireza/drywall#258]
Hi Guys,

I'm trying to add a unique nickname field to the user portion. I thought that would be better than adding it to the account section, because I wanted it unique for comment posting between users.

I'm having trouble getting it to insert into the database on an account create and update. When I do the signup, everything goes through, but the nickname field isn't inserted into the database. When I try to do the update, it complains that the field is required, even when there is something in the field.

Listed below are the places that I added code for the nickname field. Can someone suggest what I might be missing?

Thanks,

Fred

schema/User.js  - Added to user schema as a unique string, and also to the index entries.

views/account/settings/index.jade - Added field to the indentity template, including the errfor field.

views/account/settings/index.js - Added checks for required field, added a duplicate nickname check function to the workflow, added nickname to the fieldsToSet on patchuser, added nickname to the options.

views/signup/index.jade - Added nickname field to signup form

views/signup/index.js - Added check for req.body.nickname in the validate function, added a duplicateNicknameCheck function to verify uniqueness, added nickname to the createUser function in the fieldToSet field.

**Comment by jedireza** [comment]
How does your `nickname` field differ from the `username` field? I know it doesn't matter to help debug this... but I'm still curious.

For the most part, the changes you mentioned sounds right. But in order to help find what exactly isn't working, would you be willing to create a fork of Drywall and make those changes you mentioned above so myself or someone else could look at it?

**Comment by mitijain123** [comment]
@fgruner @jedireza 

you had did all the right with respect to the signup process, one thing is missed out and I don't know why those files lies in 2 different places in drywall.

Please change the file in public/views/signup/index.js add your custom fields there so it will take effect.

Hope this will help.

**Comment by jedireza** [comment]
@fgruner any updates? Can we close this issue yet?

**Comment by fgruner** [comment]
I’ll get to this in the next 2 days. I’ll have an update shortly.

 

Thanks.

 

Fred

**Comment by jedireza** [comment]
What's the latsest?

**Comment by jedireza** [comment]
Closing. Let's re-open if you still need help.
