### ISSUE TITLE
Adding new blank pages

### ISSUE THREAD

**Issue by uziiuzair** [jedireza/drywall#259]
Hi,

I wanted to know how I would be able to add blank pages to the Admin section?
I created the menu and added the route to it:

```
app.get('/admin/content-blocks/', require('./views/admin/content-blocks').init);
```

The above gave me a server error. Then I tried 

```
app.get('/admin/content-blocks/', require('./views/admin/content-blocks/index').find);
app.post('/admin/content-blocks/', require('./views/admin/content-blocks/index').create);
```

But the above did not work at all, node does not start.

Could you tell me how I could just add a blank page? :/ I did it somehow before, Can't figure out this time

**Comment by jedireza** [comment]
Would you be willing to share some code examples and what errors you're getting?

**Comment by jedireza** [comment]
Closing for now.
