### ISSUE TITLE
Two Step Verification

### ISSUE THREAD

**Issue by brooklyn-xx** [jedireza/drywall#260]
I need to add two step verification to the sign in process for my drywall app. I already have it working using Twilio, but I'm popping up the verification screen at another point in the app, not at sign in. I realized I need to have it integrated with the sign in. Any advice or recommendations on how to do this? I can check in everything after it is done, not sure what the process is for that either. The app needs email verification first, then the SMS verification.

**Comment by jedireza** [comment]
Inside of routes where we ensure a valid account:
https://github.com/jedireza/drywall/blob/master/routes.js#L19-L29

You could modify `ensureAccount` so after email verification, you check for sms verification. Maybe something like this:

```js
function ensureAccount(req, res, next) {
  if (req.user.canPlayRoleOf('account')) {
    if (req.app.config.requireAccountVerification) {
      if (req.user.roles.account.isVerified !== 'yes' && !/^\/account\/verification\//.test(req.url)) {
        return res.redirect('/account/verification/');
      }
      if (req.user.roles.account.isSmsVerified !== 'yes' && !/^\/account\/verification\/sms\//.test(req.url)) {
        return res.redirect('/account/verification/sms/');
      }
    }
    return next();
  }
  res.redirect('/');
}
```

You'll also need to:

 - add an `isSmsVerified` property to the Account schema.
 - create the route and handler for `/account/verification/sms/`
 - probably some other things that are not coming to mind at the moment

Hope that helps.

**Comment by brooklyn-xx** [comment]
Thanks!

I think I have it working now.. do you want the code contributed back in the project? If so, what is the best way to go about doing this?

I'll have it working on a public site as soon as I've done a bit more testing so you could see how it operates.

One feature in my implementation that might not work for everybody is, I'm using the phone number as the username. So on the initial sign in, I just changed the name from "user" to "phone number", with a check that ensures that people only enter 10 digits. This is because in my particular application, I'm mostly concerned with limiting people to one account per person. One account per phone is good enough. So when I'm verifying the phone number with an SMS code, I'm really verifying the user name, meaning I'm sending the code to via SMS to the username. Maybe you'd prefer to keep the user name and the phone separate.

**Comment by jedireza** [comment]
Good to hear @brooklyn-xx. I think this type of feature is best served as a wiki article instead of adding it to the project source. How's that sound?

Closing the issue. You can still post here to discuss the wiki article.
