### ISSUE TITLE
What is the best way to secure MongoDB on drywall?

### ISSUE THREAD

**Issue by MadmanSmoker** [jedireza/drywall#261]
I am using drywall and would like to know what are the steps involved to setup a username and password and access the mongodb account on drywall. From what I have read lets say I am using a database called drywall , then 
use admin
db.createUser(
  {
    user: "siteUserAdmin",
    pwd: "password",
    roles: [ { role: "userAdminAnyDatabase", db: "admin" } ]
  }
)

and use the syntax mongodb://username:password@host:port/db.

So my questions are with my default mongo configuration can anyone access my database or is it only restricted through the nodejs program?
What is the best way to secure the database and also where exactly do we insert the line  mongodb://username:password@host:port/db.
. I am new to Mongodb, hence the question

**Comment by jedireza** [comment]
Thanks for creating an issue. Securing MongoDB isn't something Drywall helps you with. A Drywall user account is not related to MongoDB administration. I'd elect to go with a service like MongoLab or MongoHQ before rolling your own server.

If I misinterpreted your question let me know.
