### ISSUE TITLE
Launch video/webm on Android or generic mobile. Request Authentication.

### ISSUE THREAD

**Issue by lags** [jedireza/drywall#263]
Hi,
with drywall i've develope an app which store video from users into mongodb via gridfs. These video can play only for own user.
If user is logged into website with pc via browser (ex: chrome) and click for watching a video (ex: http://mysite/watch/12345678.webm), all it's ok; video play correctly but If user is logged into website by mobile (ex: android or ios) and click for watching a video (ex: http://mysite/watch/12345678.webm), for play video, system's mobile launch internal player with error 'Failed to load resource' and into log of server the route http://mysite/watch/12345678.webm redirect to http://mysite/login because the player isn't autenticate. These videos are private so authentication is required. Someone can help me? Thanks in advance.

**Comment by jedireza** [comment]
Thanks for creating an issue. That's an interesting question. Doing some quick googling I found this:

http://stackoverflow.com/a/3767927/1410672

**Comment by jedireza** [comment]
I'm going to close this issue for now since it doesn't seem like an issue with Drywall.

Good luck with your project. I'd like to hear about it when you launch.
