### ISSUE TITLE
Planning v1.0.0

### ISSUE THREAD

**Issue by jedireza** [jedireza/drywall#268]
We're overdue for some upgrades to code and delivery. I'd like to start charting the path to a v1.

There are some architecture changes:

 - [ ] Separate API and web serving
    - [Frame](https://github.com/jedireza/frame) is the heart of the Drywall API rebuilt in Hapi. In it's current state it serves as a good example of how we can totally separate our API from our web server. We should do the same thing in Drywall, but I'd like to see us keep using Express. I think it would serve as a good example of a larger app built with both server frameworks.
    - We can reuse a lot of the code in Frame.
    - I plan to use the same coding standards as Frame.
    - One big question is if we should stop using [Mongoose](http://mongoosejs.com/). I'd like to see us using a much simpler modeling tool like [`hapi-mongo-models`](https://github.com/jedireza/hapi-mongo-models). Maybe that module could get updated to provide an Express middleware.
 - [ ] Updated front-end build and workflow
    - Backbone is very plain. I've worked with [Ampersand](http://ampersandjs.com/) and think it's a great step up from Backbone.
    - We can DRY up our views quite a bit with a little view composition
 - [ ] Better dev mode
    - We should start the app like `$ npm start` instead of running `$ grunt directly`

__Older issues__ that we don't want to leave behind without more thought:

 - [ ] Use [nodemailer](https://github.com/andris9/Nodemailer) instead of [emailjs](https://github.com/eleith/emailjs)
 - [ ] A better build for front-end assets (js and css)
    - Hopfully we can add css/less source maps
 - [ ] Adding i18n support
 - [ ] Tests
 - [ ] Faster permission lookups (#291)

**Comment by solomongifford** [comment]
Also consider angular.js instead of backbone.

**Comment by ru108** [comment]
1. Keeping Express
2. Keeping Mongoose
3. Front-end - reatcjs + Flux

IMHO

**Comment by jedireza** [comment]
@ru108 good news... I just published a new version of Drywall called [Aqua](https://github.com/jedireza/aqua/). It takes from the [Frame](https://github.com/jedireza/frame/) API and implements the front-end with React and Flux.

I'd like to keep Drywall as the Express/MVC version to demonstrate how to implement a similar, decent sized, app with pretty different architectures.

I'd still like to get rid of Mongoose and use Ampersand instead of Backbone.

**Comment by ru108** [comment]
Reza, thank you very match for code!
Its the best boilerplate for users admin.

Aqua looks promising!

**Comment by davew252** [comment]
I happily and gratefully chose this system - (after 2 years of core app development and finally a months-long-part-time agonizing DIY/TrialAndError/Search approach to implementing "User Account Management", the last major piece of required functionality) - precisely BECAUSE it used everything I was already using and familiar with - Node.js, Express, Mongoose, and indirectly Backbone (by way of YUI Framework - yeah. Stupid me. Live and learn. Done a lot of both, thanks. Maybe too much.).
I've only recently begun learning/experimenting with/implementing Drywall. I am committed to its use, AS IS, for the foreseeable future.
Removing Mongoose probably wouldn't kill me. I could deal with it.
But I have neither the desire, the time, nor the energy to learn and incorporate "&yet" another front-end architecture, e.g. Ampersand, pardon the pun. Or React/Flux. Or anything else.
I'm glad to see you created a new project for Aqua.
What are your plans/thoughts for maintaining, or encouraging the maintenance of, this app, AS IS, at least for the next 6-8 mos. or so?
Thanks for your efforts and attention.

**Comment by jedireza** [comment]
> I happily and gratefully chose this system - [...] - precisely BECAUSE it used everything I was already using and familiar with - Node.js, Express, Mongoose, and indirectly Backbone

I'm glad you like the project, it's always good to hear. These technologies are a great combo. If you're dedicated to using them, just be sure to identify where key improvements can be made (which is the goal for this thread) and you should be in great shape.

> What are your plans/thoughts for maintaining, or encouraging the maintenance of, this app, AS IS, at least for the next 6-8 mos. or so?

I always like to say _"What you build with Drywall is more important than Drywall"_, which is true. Boilerplate apps (aka starters) are just a jump off point. Once you start customizing, it's all yours. And what you make is way more important than the tech stack you're using.

I think the best path for maintaining a boilerplate project is to keep it relevant. Sometimes that could mean changing things.

- - - - -

:+1: Thanks for bringing up these points and questions.

**Comment by davew252** [comment]
OK. Fair enough. Thanks.

**Comment by metasection** [comment]
Backbone - keep

**Comment by jedireza** [comment]
> Drywall is completely awesome. We love it.

Always great to hear. Thanks. :pray: 

> Separate API - can we come up with a project structure that allows everything to be run on one site/domain? Getting a small project up and running with multiple hosts might be trouble for some.

Yes, starting with multiple hosts is not great for small projects. Aqua has a very clean separation between the api and the web server, but they're both on the same server, that's what I was getting at.

> Swagger, Customer.io, Debug module and Responsive email templates.

I consider all this stuff outside the scope of what Drywall should focus on.

> One challenge that we have with project structure... We would like to have third party designer work on the Jade views, styles, etc. We don't want to give them access to the controller logic or backbone stuff. Is there a project structure that would support this?

Sounds icky if they're not going to commit to the project repo. If you want them on an island, you'll probably have to bring their changes into your project manually. This is a bit off topic. :wink:

**Comment by klh** [comment]
just use i18next as mentioned above, it support both client side and server side.
and has a webtranslate gui as well as string extraction, tried most of the libs out there and it is the easiest to implement, tons of generators aswell.\

http://i18next.com/
&
http://i18next.com/node/ (support for middleware etc.)


* support for variables 
* support for nesting 
* support for context 
* support for multiple plural forms  
* gettext support 
* sprintf supported 
* detect language 
* graceful translation lookup 
* jquery function 
* get string or object tree 
* get resourcefiles from server 
* resource caching in browser
* post missing resources to server 
* highly configurable 
* custom post processing 
* translation ui 

http://i18next.com/pages/ext_webtranslate.html
https://github.com/ckir/i18next-meteor/
https://github.com/mikefrey/i18ng
http://i18next.com/pages/ext_i18next-conv.html
https://github.com/auxilium/i18next-editor
https://github.com/rbeere/i18next-jade-express-sample

**Comment by rezakhanmirzaee** [comment]
Is there any plan to add support for two factor authentication in this project ?

**Comment by kaleguy** [comment]
I've added a two factor implementation to my installation of drywall. I'll add it as a wiki article by Monday or Tuesday.

**Comment by jedireza** [comment]
> Is there any plan to add support for two factor authentication provider in this project ? ASP.NET Identity 2.1 supports it but I found a few modules implemented this feature in node.js.

No. This is something that should be done by the developer.

> I've added a two factor implementation to my installation of drywall. I'll add it as a wiki article by Monday or Tuesday.

That would be great. I look forward to it.

**Comment by kaleguy** [comment]
The wiki doesn't seem to be editable.. what is the best way to add a page? I tried forking but it looks like the wiki doesn't get pulled.

**Comment by jedireza** [comment]
@kaleguy for now just create a gist.

**Comment by kaleguy** [comment]
How's this:
https://gist.github.com/kaleguy/451dd16a9df25ab7e9e0

There's a couple of new untested lines in there, because the email from my local machine is not functioning and I couldn't test the whole workflow. I'll be testing it on my server soon. Should be OK though.

**Comment by jedireza** [comment]
@kaleguy very cool. I've added a link to your gist in the wiki.

https://github.com/jedireza/drywall/wiki#other-guides

**Comment by refactorized** [comment]
I have been looking at [waterline](https://github.com/balderdashy/waterline) for a project I'm working on.  It is a database normalization layer allowing access to underlying stores to use a consistent api.  

It might be worth simply keeping the existing mongoDB setup, but shimming this in between to give implementers ultimate flexibility.  

Take this with a grain of salt though, I have not actually used waterline yet.

**Comment by jedireza** [comment]
Thanks for sharing @refactorized. There's also [bookshelf.js](http://bookshelfjs.org/) which works with PostgreSQL, MySQL, and SQLite3. I never dug into tools like these because the use case of swapping out the db engine never arose.

**Comment by dstroot** [comment]
What about maybe using https://github.com/OptimalBits/node_acl for access cotntrol?  One of the strong points with this is the ACL side in Admin.

**Comment by jedireza** [comment]
@dstroot that's pretty cool. I hadn't seen that before. Thanks for sharing.

**Comment by quangmydn** [comment]
You can add cluster to run drywall on multicore. I run app on prot 8000 and i want other on port 8001 from 1 folder? Have I copy app folder and change port? I want scale app.  Thanks for great example app for newbie !

**Comment by jedireza** [comment]
@quangmydn thanks for commenting. A wiki page about using `cluster` is probably a good idea. For the time being I suggest reading more about this here:

 - https://nodejs.org/api/cluster.html
 - https://devcenter.heroku.com/articles/node-cluster

**Comment by billymwlei** [comment]
Can you allow choosing between Jade and EJS?

**Comment by jedireza** [comment]
@billymwlei thanks for chiming in. We probably wont' support more than one template language. It would inflate maintenance. This is one of those decisions that suck for creating boilerplates. If you haven't already checkout [Frame](https://github.com/jedireza/frame/), which is the core API of Drywall, using the hapijs framework, but without a front-end.

**Comment by jedireza** [comment]
I'm closing this issue since I'd use Frame or Aqua these days. Also duplicating the work in those projects using express/backbone is hard for me to justify with my current workload. :v:
