### ISSUE TITLE
navbar items by permission

### ISSUE THREAD

**Issue by SemonCat** [jedireza/drywall#270]
Hi,

Thanks for your develop.

I want make navbar list by user permission.

Can you give me some advance?

BR.

**Comment by jedireza** [comment]
You could show items one-by-one or via some abstracted configuration. I've done something similar before in `/layouts/admin.jade` where I wanted to show different nav items based on Admin Group.

Here is an example of how you could show items based on Admin Group:

https://github.com/jedireza/drywall/blob/master/layouts/admin.jade#L21

```js
div.navbar-collapse.my-navbar-collapse.collapse
  ul.nav.navbar-nav
    li.dropdown
      a.dropdown-toggle(href='#', data-toggle='dropdown')
        | System&nbsp;
        span.caret
      ul.dropdown-menu
        li.dropdown-header Pivoted Settings
        li: a(href='/admin/statuses/') Statuses
        li: a(href='/admin/categories/') Categories
        // *** only show these items to root admins ***
        if user.roles && user.roles.admin.isMemberOf('root')
          li.divider
          li.dropdown-header User Admin
          li: a(href='/admin/users/') Users
          li: a(href='/admin/accounts/') Accounts
          li: a(href='/admin/administrators/') Administrators
          li: a(href='/admin/admin-groups/') Admin Groups
  form.navbar-form.pull-right#_search
```

You could use `user.roles.admin.hasPermissionTo('setting')` too, but that seems like a lot to setup and maintain. Before I use permissions, I always ask if I could divide users into groups to accomplish my goal.

Does this answer your question?

**Comment by SemonCat** [comment]
Thanks for your reply,

but I can't get user.roles at jade,it's always return empty.

It's a lazy load field?

**Comment by SemonCat** [comment]
OK,

I found the place to load roles.

Work well.

Thanks very much.

**Comment by jedireza** [comment]
:sparkles: awesome :sparkles:
