### ISSUE TITLE
How to integrate drywall as a express subapplication? 

### ISSUE THREAD

**Issue by irrwitz** [jedireza/drywall#272]
Hi Reza,

thanks a lot for the drywall project. One thing which is not clear to me is, how should I integrate drywall within an existing express application? 
My application is mounted on `'/`' and drywall is mounted at `'/a'` (app.use('/a', drywall)). If I now goto e.g. `localhost:3000/a/` the view is rendered but it can't find the resources because it is looking under `'/layouts/core.min.js?br34k-01'` instead of `'/a/layouts/core.min.js?br34k-01'`, because it does not know that it is mounted at `'/a'`. 
Is there a single place where I can tell drywall (or via express) that it is mounted at `'/a/'`? I want to change as little as possible, because whenever I upgrade drywall I probably would need to apply the changes again. 

Thanks a lot for your time,
Joshy

**Comment by jedireza** [comment]
The original intent was to start a new app with Drywall. Currently we don't have a way to configure it to be mounted at a different base path.
