### ISSUE TITLE
Sub Users support?

### ISSUE THREAD

**Issue by metasection** [jedireza/drywall#274]
Does Drywall have the concept of a sub-user?

Example:  User A creates Account 1.  User A then invites a bunch of other people to join (User B, C, ...).  User B and C can login and do limited stuff with data associated with Account 1.

Is there a recommended implementation strategy for something like this?

**Comment by ak0815** [comment]
+1

**Comment by luchasei** [comment]
+1

**Comment by jedireza** [comment]
Great question. Thanks for opening an issue.

> Does Drywall have the concept of a sub-user?

Not by default.

> Is there a recommended implementation strategy for something like this?

One way this could be accomplished is by creating an __Organization__ abstraction. Maybe create an Organization model and create references to it from the users/admins/accounts models.

_Organization schema:_

```js
var organizationSchema = new mongoose.Schema({
  _id: { type: String },
  name: { type: String, default: '' },
  owners: [{
    id: { type: mongoose.Schema.Types.ObjectId, ref: 'Account' },
    name: { type: String, default: '' }
  }]
});
```

Extending the other schemas with an organization reference:

```js
var otherSchema = new mongoose.Schema({
  organization: {
    id: { type: mongoose.Schema.Types.ObjectId, ref: 'Organization' },
    name: { type: String, default: '' }
  },
  // ...
});
```

You also have to consider how this affects uniqueness of things like usernames and email addresses. Can there be two `jedireza` users if they are in different organizations? If so you'll need to update a bunch of login/session login and probably update a bunch of queries checking for duplicate username/email usage throughout the app.

- - - - -

If you give this a shot I'd love to see your progress.

**Comment by metasection** [comment]
This makes a lot of sense.  Like the approach.  We have a programmer on our team that is very good with this sort of thing.  I will check the schedule and see what we can do.  Hopefully get some time on this in March.
