### ISSUE TITLE
fix bad links in Dependency & Asset Check ins wiki page

### ISSUE THREAD

**Issue by exyzzy** [jedireza/drywall#275]
in: 
https://github.com/jedireza/drywall/wiki/Dependency-%26-Asset-Check-ins

https://docs.npmjs.com/faq#Should-I-check-my-node_modules-folder-into-git
should be:
https://docs.npmjs.com/misc/faq#should-i-check-my-node_modules-folder-into-git

http://www.futurealoof.com/posts/nodemodules-in-git.html
www.futurealoof.com is down

**Comment by jedireza** [comment]
Thanks for letting me know. I fixed the npm link. I'm waiting to hear back if the futurealoof.com outage is temporary.

**Comment by jedireza** [comment]
Yup futurealoof.com is gone. I updated the link to use archive.org.
