### ISSUE TITLE
Question:About Backbone app

### ISSUE THREAD

**Issue by prasad8mhatre** [jedireza/drywall#279]
Respected Sir,
I am building a 'Secured cloud storage' project.
Details of project are:-
server side: mongodb+express+nodejs
client side: Backbonejs
The idea is to encrypt the user's file at client side on browser
itself using backbone js,
and then store that encrypted files on server on mongodb or Sever Filesystem.

As I am newbie to Js technology.
So, i searched on internet,I found "NodeCellar: Sample Application
with Backbone.js, Twitter Bootstrap, Node.js, Express, and MongoDB"
<http://coenraets.org/blog/2012/10/nodecellar-sample-application-with-backbone-js-twitter-bootstrap-node-js-express-and-mongodb/>

So, in order to solve this problem,I first defined my dummy database
so as i could access it.
Then,next step is to create a RESTfull api for accessing/manipulating
that data.And for doing this,i need to go with node.js and express.js.
So, i started creating a routes for my app.
And later that Need to create backbone app.

Question:I have created <Model> for "File",And "Files" <collection> in /public .
And for "http://localhost:3000/account/files/" route i able to get retrieve my data from db.

So, how can i create a <view> for the data and attached to element in the "account" template?  

Would you able to help me sort this problem.
Hoping for your kind favor.

**Comment by jedireza** [comment]
Thanks for opening an issue. I've read the details of your question a few times and I'm having trouble fully understanding the issue that is blocking you.

Did you start a project using Drywall as the starter or did you start from scratch? I'm also not seeing how the nodecellar example ties in.

It's important to understand the tools Drywall is built. Drywall is just using all these modules in concert. Maybe you could try to narrow the focus to some specific/reproducible code snippet(s).
