### ISSUE TITLE
less compilation fails (tested on Ubuntu and Windows 8)

### ISSUE THREAD

**Issue by vjjjv** [jedireza/drywall#281]
Command "grunt" kept failing with error:

```
>> Running "less:layouts" (less) task
>> NameError: variable @form-group-margin-bottom is undefined in public\vendor\bootstrap\less\forms.less on line 205, column 18:
>> 204 .form-group {
>> 205   margin-bottom: @form-group-margin-bottom;
>> 206 }
>> Warning: Error compiling public/less/bootstrap-build.less Use --force to continue.
>> Aborted due to warnings.
```

The fix was to add this to the beginning of bootstrap-build.less:

```css
// Core variables and mixins
@import "../vendor/bootstrap/less/variables.less";
```

After adding that "less" commands work fine and also the whole Drywall site seems to be working fine.

**Comment by vjjjv** [comment]
This is the working version of my drywall\public\less\bootstrap-build.less

```javascript
// Core variables and mixins
@import "../vendor/bootstrap/less/variables.less";
@import "bootstrap-vars.less";
@import "../vendor/bootstrap/less/mixins.less";

// Reset
@import "../vendor/bootstrap/less/normalize.less";
@import "../vendor/bootstrap/less/print.less";

// Core CSS
@import "../vendor/bootstrap/less/scaffolding.less";
@import "../vendor/bootstrap/less/type.less";
@import "../vendor/bootstrap/less/code.less";
@import "../vendor/bootstrap/less/grid.less";
@import "../vendor/bootstrap/less/tables.less";
@import "../vendor/bootstrap/less/forms.less";
@import "../vendor/bootstrap/less/buttons.less";

// Components
@import "../vendor/bootstrap/less/component-animations.less";
@import "../vendor/bootstrap/less/glyphicons.less";
@import "../vendor/bootstrap/less/dropdowns.less";
@import "../vendor/bootstrap/less/button-groups.less";
@import "../vendor/bootstrap/less/input-groups.less";
@import "../vendor/bootstrap/less/navs.less";
@import "../vendor/bootstrap/less/navbar.less";
@import "../vendor/bootstrap/less/breadcrumbs.less";
@import "../vendor/bootstrap/less/pagination.less";
@import "../vendor/bootstrap/less/pager.less";
@import "../vendor/bootstrap/less/labels.less";
@import "../vendor/bootstrap/less/badges.less";
@import "../vendor/bootstrap/less/jumbotron.less";
@import "../vendor/bootstrap/less/thumbnails.less";
@import "../vendor/bootstrap/less/alerts.less";
@import "../vendor/bootstrap/less/progress-bars.less";
@import "../vendor/bootstrap/less/media.less";
@import "../vendor/bootstrap/less/list-group.less";
@import "../vendor/bootstrap/less/panels.less";
@import "../vendor/bootstrap/less/wells.less";
@import "../vendor/bootstrap/less/close.less";

// Components w/ JavaScript
@import "../vendor/bootstrap/less/modals.less";
@import "../vendor/bootstrap/less/tooltip.less";
@import "../vendor/bootstrap/less/popovers.less";
@import "../vendor/bootstrap/less/carousel.less";

// Utility classes
@import "../vendor/bootstrap/less/utilities.less";
@import "../vendor/bootstrap/less/responsive-utilities.less";

// Theme
@import "bootstrap-theme.less";`
```

**Comment by yorkperry** [comment]
I got the same error:

>> Running "less:layouts" (less) task
>> NameError: variable @form-group-margin-bottom is undefined in public/vendor/bootstrap/less/forms.less on line 205, column 18:
>> 204 .form-group {
>> 205   margin-bottom: @form-group-margin-bottom;
>> 206 }
Warning: Error compiling public/less/bootstrap-build.less Use --force to continue.

>>Aborted due to warnings.

I have run bower and npm cache clean's with no luck:
$ bower cache clean
$ npm cache clean

Setup Details:
$ node -v 
v0.10.29
$ npm -v 
v2.7.5
$ grunt --version
grunt-cli v0.1.13
grunt v0.4.5
OSX: 10.10.2

**Comment by alexleventer** [comment]
Thanks @vjjjv, that worked for me.

**Comment by jedireza** [comment]
Should this issue be closed? Or are there updates needed?

**Comment by vjjjv** [comment]
At least for me, on Windows8 and Linux Ubuntu, I have to make this change to be able to start with grunt:

The fix was to add this to the beginning of bootstrap-build.less:
// Core variables and mixins
@import "../vendor/bootstrap/less/variables.less";

..a and according to comment from @alexleventer problem occurs for others too.

**Comment by yorkperry** [comment]
The added line to the bootstrap-build.less file is working for me as well. 
 
--------- Original Message --------- Subject: Re: [drywall] less compilation fails (tested on Ubuntu and Windows 8) (#281)

**Comment by alexleventer** [comment]
The suggested line by @vjjjv needs to be added.

**Comment by gooooloo** [comment]
@vjjjv Thanks, it works.

**Comment by jedireza** [comment]
I was able to reproduce this. This actually happens when Bootstrap changes their build variables. Since we have a copy of that file in `/public/less/boostrap-vars.less` it can get out of date.

Commit 8d0818415086a399f3cfa1d5a5d12ffca093dede is the actual fix. It's included in PR #284.

**Comment by Brian1111** [comment]
I have entered the following codes, yet I am getting errors that less variables wasn't found:
@import "bootstrap-vars.less";
@import "../vendor/bootstrap/less/variables.less";
@import "../vendor/bootstrap/less/mixins.less";

This is the error message:
FileError: '../vendor/bootstrap/less/variables.less' wasn't found.
2 @import "bootstrap-vars.less";
3 @import "../vendor/bootstrap/less/variables.less";
4 @import "../vendor/bootstrap/less/mixins.less";
Warning:  Error compiling public/less/bootstrap-build.less  Use --force to continue.
Aborted due to warnings.

**Comment by jedireza** [comment]
@Brian1111 please pen a new issue with what you just posted.

**Comment by Brian1111** [comment]
@jedireza Thank you for your reply.  I could fix the problem by running "npm update" at command prompt.
