### ISSUE TITLE
i get this error when is use grunt command..please help

### ISSUE THREAD

**Issue by brkeerthi** [jedireza/drywall#282]
C:\drywall\drywall>grunt
Running "copy:vendor" (copy) task
Created 5 directories, copied 108 files

Running "newer:uglify" (newer) task

Running "newer:uglify:layouts" (newer) task
No newer files to process.

Running "newer:uglify:views" (newer) task
No newer files to process.

Running "newer:less" (newer) task

Running "newer:less:layouts" (newer) task
No newer files to process.

Running "newer:less:views" (newer) task
No newer files to process.

Running "concurrent:dev" (concurrent) task
Running "nodemon:dev" (nodemon) task
Running "watch" task
Waiting...
[nodemon] v1.3.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUN

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUN

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUN

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUN

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUN

js-bson: Failed to load c++ bson extension, using pure JS version

##############################################################
#
#   !!! MONGOOSE WARNING !!!
#
#   This is an UNSTABLE release of Mongoose.
#   Unstable releases are available for preview/testing only.
#   DO NOT run this in production.
#
##############################################################

mongoose connection error:  [Error: failed to connect to [localhost:27017]]

C:\drywall\drywall\node_modules\connect-mongo\node_modules\mongodb\lib\serve
:228
        process.nextTick(function() { throw err; })
                                            ^
Error
    at Object.<anonymous> (C:\drywall\drywall\node_modules\connect-mongo\nod
dules\mongodb\node_modules\mongodb-core\lib\error.js:42:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\drywall\drywall\node_modules\connect-mongo\nod
dules\mongodb\node_modules\mongodb-core\index.js:2:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
[nodemon] app crashed - waiting for file changes before starting...
^CTerminate batch job (Y/N)? y

C:\drywall\drywall>node start
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\drywall\drywall\start'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by brkeerthi** [comment]
fixed it..
i forgot to start the mongo server.
and
i had to udate the mongoose version in the pakage.json file
works awesome!! thanks a lot

**Comment by jedireza** [comment]
> works awesome!! thanks a lot

Glad to hear you got it working. :fireworks:
