### ISSUE TITLE
A blog post feature would integrate nicely into Drywall.js

### ISSUE THREAD

**Issue by cojomojo** [jedireza/drywall#286]
I have been using drywall for a bit now and I think a blog post feature is worth including. Yes, it is relatively simple to implement your own, but I think that it would be used enough to warrant being a feature of drywall itself. It would also offer a great example for what you can do with categories.

**Comment by jedireza** [comment]
Thanks so much for getting involved and creating a pull request! :+1:

> Yes, it is relatively simple to implement your own, but I think that it would be used enough to warrant being a feature of drywall itself.

You're right that it's simple to implement. And when a feature is simple to implement it's usually a signal that it should be left out of the project. Take these simple features for example:

 - [Using reCAPTCHA](https://github.com/jedireza/drywall/wiki/Using-reCAPTCHA)
 - [Added Email Verification with Social Sign Up](https://github.com/jedireza/drywall/wiki/Added-Email-Verification-with-Social-Sign-Up)

They're simple and useful. But they bring opinions along for the ride. In your blog example you use the `medium-editor` for example, maybe someone would rather use `ckeditor`.

> It would also offer a great example for what you can do with categories.

Yup. I've done this myself.

- - - - - -

Like the features mentioned above, I think it's best to create a wiki article out of this instead. That way anyone who starts and/or started a project with Drywall could implement them as they see fit.

Also keep in mind that it's time for a serious upgrade to Drywall as we're discussing in #268 (Planning v1.0.0). I think
