### ISSUE TITLE
Integration with Auth

### ISSUE THREAD

**Issue by refactorized** [jedireza/drywall#288]
Once I have Drywall set up and handling my user creation and management, how do I actually use these users to log in to my App?  

Is it expected that I will use something like Passport's local strategy and just feed from the same DB?

Or does Drywall provide some sort of SSO functionality too?  

Also, how is all of this affected by the use of subdomains?

Thanks

**Comment by jedireza** [comment]
> Once I have Drywall set up and handling my user creation and management, how do I actually use these users to log in to my App?

Your copy of Drywall is the app you'd login to. By default it's not an OAuth provider provider itself. You may want to checkout https://github.com/jaredhanson/passport-oauth2. I think this is similar to #169 if I'm not mistaken.

Apologies if I misunderstood the question. Let me know if this helps.

**Comment by refactorized** [comment]
Sorry to let this close, and thanks for your efforts to answer.  I am not looking for Oauth per se.   Let me try to articulate this better.  

Let's say I am creating a simple todo program.  I will need to have pages for user registration, administration of those users, profile data etc.  It seems that drywall handles most or all of that out of the box.  

Then I will need to code pages/functions for entering and viewing todo lists, and those pages will need to know what user is active, and their details.  So how should I go about doing this, or is it even a feature that drywall is supposed to provide?

I am going to try to answer that myself with some perusal through the source, but please let me know if there is some intended way to interact with user login and data from within the code of the greater application.  

Thanks ,
Adam

**Comment by jedireza** [comment]
Checkout the `/account` area and related pages. For example `/account/settings` allows the currently logged in account to update their settings. You could do something similar and manage other data like todo lists and items.
