### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by zevero** [jedireza/drywall#289]
Installation as proposed in the readme

    $ git clone git@github.com:jedireza/drywall.git && cd ./drywall
    $ npm install

does not work and could put off newcomers.
Please replace with

    $ git clone https://github.com/jedireza/drywall.git && cd ./drywall
    $ npm install

Thank you!

**Comment by jedireza** [comment]
You may want to take a look at https://help.github.com/articles/which-remote-url-should-i-use/

> When you `git fetch`, `git pull`, or `git push` to the remote repository using HTTPS, you'll be asked for your GitHub username and password.

Which is why I like the ssh route. Thanks for creating an issue. I'll keep this in mind in the future.

**Comment by zevero** [comment]
Thank you for the link!
Sure, if you have your ssh route set up for github its easier and the experienced of us will do it in this way.
For newcomers however the https route is easier, because it does not require username and password.
