### ISSUE TITLE
Angular & Drywall Authentication

### ISSUE THREAD

**Issue by existeundelta** [jedireza/drywall#290]
Hi Reza,

  I want to connect an Angular App(web app), to drywall, basically the authentication (login), can you help me in finding the best option?

Thanks!

**Comment by jedireza** [comment]
I haven't used Angular myself. [Frame](https://github.com/jedireza/frame) is the core Drywall API using Hapi instead of Express. I know that @Silom was working on creating an Angular front-end to it. https://github.com/Silom/ngFrame

**Comment by jedireza** [comment]
Also, [Aqua](https://github.com/jedireza/aqua) is a React/Flux implementation that was built on top of Frame. :wink:

**Comment by existeundelta** [comment]
Thanks, I was confused, I thought Drywall was using Express...
But, not thinking in frameworks, if  i want a html page to with email and pass do a login to drywall, do you think is possible an easy?  like http://passportjs.org/docs/username-password , do you think is posible to submit it to /login and  then get something I imagine the auth token and save it in the same way Drywall uses?

Thanks

**Comment by jedireza** [comment]
Drywall does use Express. Frame and Aqua use Hapi. Frame is more properly setup as an API where you would simply POST to `/login` and get the response back.

**Comment by existeundelta** [comment]
Thanks! really is posible to submit email to /forgot  in Drywall for example and it works
I think I din't understand it correctly, you mean that i can install Frame on the top of Drywall to have a better solution for having an API? and they work fine together?
I already do a /login to Drywall and get a Json with success or fail, but now I don't have it clear how to access the user, is all done throw connect.sid? if there is a link/tip where I can understand it all better I would apprecciate it a lot! thanks!
Thanks!

**Comment by Silom** [comment]
@existeundelta check out the login example from ngFrame. ngFrame uses almost all of the API from Frame.

Frame and Drywall are two different things. Frame is an Restful API and Drywall ist a more old school static file serving webserver (with jQuery to make it feel dynamic). Also in Frame you don't have a frontend included, thats why there are implementations such as Aqua and ngFrame.

In web you try to separate between front- and backend. If you use an Rest-API interface, you can easily archive this by defining the payload that goes out und in (its all based on http level).

Check this [file](https://github.com/Silom/ngFrame/blob/master/src/modules/login/service/login-factory.js), here you can see how ngFrame sends a response to the Frame-API.

**Comment by jedireza** [comment]
Thanks @Silom :+1:

- - - - - -

Based on the comments you've created in other issues, I get the impression that you're moving fast and trying to get something working quickly. It's important that you understand the underlying modules and technologies.

We're not doing anything fancy or magical, I'd recommend spending some time taking things apart and figuring out how they work. When you come across a new module you haven't seen before, go checkout their docs.

Thanks for getting involved. Always feel free to ask questions. :pray:

**Comment by existeundelta** [comment]
Thanks @Silom, I Understand the difference between Frame and Drywall, but if i already have Drywall with some things done, can I install Frame on top of it and take advantage of the two? with the only element in common will be the Models and MongoDB?

@jedireza  yes you are right, my background is bit old, mainly in ASP.NET and "old" javascript 

Thanks! I think I would continuous asking :)

**Comment by existeundelta** [comment]
I'm having problems installing ´bcrypt´ , I think my problem is with gcc that is using ´anaconda/bin/gcc´
(I also have problems installing pymc http://stackoverflow.com/questions/24853812/failure-to-import-pymc-gfortran-library-not-loaded-after-installing-from-conda)
 I read https://github.com/jedireza/frame/wiki/bcrypt-Installation-Trouble, and also arise me a question, if I have Drywall with bcrypt(I did't have problems then), and Frame with bcryptjs will work well... also I read
https://github.com/DaftMonk/generator-angular-fullstack/issues/474

Without understanding it (please tips/links wellcome :) ) if If in the future another security library is implemented what would imply for the already registered users?

**Comment by existeundelta** [comment]
Solved `bcrypt`problem install, as I thought was done because of using different gcc, solved with moving

export PATH=$HOME/bin:/usr/local/bin:$PATH

as last

**Comment by existeundelta** [comment]
I still get this error 

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

when running `npm run setup`

**Comment by jedireza** [comment]
https://github.com/jedireza/drywall/wiki/bcrypt-Installation-Trouble

**Comment by existeundelta** [comment]
Yes :) I read, but I don't want to go to the alternatives :) 
 is not an error in the installation
```
$ npm install bcrypt --save
```
 installation now works ok, is when running setup `npm run setup`

**Comment by existeundelta** [comment]
beginning again:

```
rm -rf frame
```

and git clone && npm install and now all worked well :) (:D restart solution)

**Comment by existeundelta** [comment]
directly changing mongo to a drywall seems to not work ... 
@jedireza is because models have change or may be is something more in deep and I'm trying a stupid thing? :)

**Comment by existeundelta** [comment]
I see a little change in Roles in user model, Drywall seems to have role as directly link `name of the role as the name of the property' to roles object and Frame the object has to properties `id` the link to the role object and `name`, seems better option Frame, do you think changing this thing in Drywall will solve?

**Comment by jedireza** [comment]
They're not 100% compatible since there are some differences (which you've found).

**Comment by existeundelta** [comment]
@jedireza Thanks

**Comment by existeundelta** [comment]
Hi @jedireza,

do you have or have though about, having a checklist, procedure to migrate drywall to Frame?

thanks!

**Comment by jedireza** [comment]
@existeundelta no I don't.
