### ISSUE TITLE
Using GeoLocation

### ISSUE THREAD

**Issue by pepcha** [jedireza/drywall#292]
Hi, 

I am new to Nodejs and trying to incorporate GeoLocation on Accounts and Sort them based on the location instead of Name.
Could  you please help me out to use it.

Thanks
Lavanya

**Comment by jedireza** [comment]
Thanks for opening an issue. I think this falls out of scope for this project and I don't have experience with GeoLocation. You may want to checkout http://docs.mongodb.org/manual/applications/geospatial-indexes/
