### ISSUE TITLE
filter by date

### ISSUE THREAD

**Issue by ss2k** [jedireza/drywall#294]
what would be the best way to filter the collections by date? i figured this would be a standard filter included but guess not

**Comment by jedireza** [comment]
Thanks for creating an issue. And you're right, this is standard stuff that mongo has built in.

Here are some links that might be of help.

 - http://stackoverflow.com/a/2943685
 - http://docs.mongodb.org/manual/reference/operator/query/gt/
 - http://docs.mongodb.org/manual/reference/operator/query/gte/
 - http://docs.mongodb.org/manual/reference/operator/query/lt/
 - http://docs.mongodb.org/manual/reference/operator/query/lte/

I hope this gets you in the right direction. Let us know if you still need help.

**Comment by ss2k** [comment]
thanks for the response. i know how to filter by date but i am talking about from the perspective of drywall. its more of a suggestion than an outright question, sorry for the confusion. the admin section comes with a host of filter/sorts already but what im suggesting is for filtering by date to be a standard in the later version.

also, being relatively new to drywall, i am a bit confused about:

`req.app.db.models.Category.pagedFind({
    filters: filters,
    keys: 'pivot name',
    limit: req.query.limit,
    page: req.query.page,
    sort: req.query.sort
  }, function(err, results) {`

I guess I am more confused about the pagedFind function... I can't seem to figure out where i would put the filter for the dates. Is this function part of mongoose? Thanks for your help.

**Comment by jedireza** [comment]
> its more of a suggestion than an outright question, sorry for the confusion. the admin section comes with a host of filter/sorts already but what im suggesting is for filtering by date to be a standard in the later version.

Oh I see. I'll keep that in mind. Thanks for clarifying.

> I guess I am more confused about the pagedFind function... I can't seem to figure out where i would put the filter for the dates. Is this function part of mongoose?

Ah. `pagedFind` is a mongoose plugin that you can find here:
https://github.com/jedireza/drywall/blob/master/schema/plugins/pagedFind.js

`pagedFind` uses the regular `find` method internally. You should put all your query conditions/filters in the `filters` property.

**Comment by tarekshumaila** [comment]
soo... I am having a problem with pagedFind. I cant seem to find a tweek so that I get the results reversed. 


I tried to change _id to date since I have a date field in my schema that records the date when a document is created. 

The goal: I want to get the last 8 records inserted to the schema in question. Now, I am getting the first 8 inserted documents, but that didnt work.

code:
        req.query.name = req.query.name ? req.query.name : '';
	req.query.limit = req.query.limit ? parseInt(req.query.limit, null) : 8;
	req.query.page = req.query.page ? parseInt(req.query.page, null) : 1;
	req.query.sort = req.query.sort ? req.query.sort : '_id';

	var filters = {};
	if (req.query.username) {
	filters.username = new RegExp('^.*?'+ req.query.username +'.*$', 'i');
	}


	req.app.db.models.Ad.pagedFind({
	filters: filters,
	keys: 'title price description date contactnumber category image images',
	limit: req.query.limit,
	page: req.query.page,
	sort: req.query.sort
	}, function(err, results) {
	if (err) {
	  return next(err);
	}

	if (req.xhr) {
	  res.header("Cache-Control", "no-cache, no-store, must-revalidate");
	  results.filters = req.query;
	  res.send(results);
	}
	else {
	  results.filters = req.query;
	  res.render('index', { data: results.data });
	}
	});

what do I have to do so I can get the 8 results reversed from first 8 records to last inserted 8 records? I guess I dont need to paginate it since I only want 8 records. Please help.

**Comment by tarekshumaila** [comment]
looks like I solved my problem. here is my solution:

req.app.db.models.Ad.pagedFind({
	filters: filters,
	keys: 'title price description date contactnumber category image images',
	limit: req.query.limit,
	page: req.query.page,
	sort: {date:-1} <---- add this and remove req.query.sort

Cheers
