### ISSUE TITLE
password reset request not sent

### ISSUE THREAD

**Issue by jskye** [jedireza/drywall#296]
i changed the email in config and added the root user with this email.
but it doesnt seem to be sending the reset request to my email...
also checked my spam folder.

**Comment by jskye** [comment]
nevermind. i was only deleting from the admin table and not the user table. will close once i verify its not an issue.

**Comment by jskye** [comment]
whats the easiest way to reset the db if u stuffed up initially?

**Comment by jskye** [comment]
ok i worked it out. db.dropDatabase().
but i still cant get it to send email.. hmm

i tried following the reset link and it said 
`Error Sending: Email failed to send. Error: authorization.failed`

when u say go to `http://localhost:3000/login/reset/:email/:token/`
do u mean i get the token from the db and enter it into this url?
i tried it and no success so far...

**Comment by jskye** [comment]
ok just noticed this: https://github.com/jedireza/drywall/wiki/Issues-using-Gmail-SMTP
i will try it.

**Comment by jskye** [comment]
hmm. tried changing ssl to tls no go.
google says setting not available for my account, so i musnt have 2 factor...

**Comment by jskye** [comment]
i think it is because the date for token has expired. 
im new to mongo, i havent worked out correct syntax to update yet. 
this fails:
```
db.users.update(
    { item: "000" },
    {
      $set: {  "roles.resetPasswordExpires":  ISODate("2015-06-20T18:04:40.014Z")}
})
```

**Comment by jskye** [comment]
for some reason date for root user is expired (yesterdays).
i updated the expiry date manually. 
```
db.users.update(
{ _id: ObjectId("000")},
{$set: {  "resetPasswordExpires":  ISODate("2015-06-22T18:04:40.014Z")}
});
```
then tried again to send email, still didn't work.
I then returned to db and found date reverted again to the expired date.

**Comment by jedireza** [comment]
Thanks for opening an issue. It's a bummer when email get's in the way of playing with the software.

The date being wrong (or off) in mongo won't prevent the email from being sent. It only prevents setting a new password when you use the generated forgot password link. So we should be able to deal with mongo's date setting later.

Gmail has been a pain for some (hence the wiki page). Some people have said it only works when they have 2 factor auth, for others that's not the case. It's hard to predict. They best bet is to use another email service to be totally sure. I use AWS SES and it seems to work well.

- - - - -

I removed this emailing step from the setup of [Frame](https://github.com/jedireza/frame) and [Aqua](https://github.com/jedireza/aqua), you may want to check those out too. :wink:

**Comment by jskye** [comment]
I tried with hotmail too with no luck.
Could it be the port is not specified?

smtp.gmail.com
Gmail SMTP port (TLS): 587
Gmail SMTP port (SSL): 465

smtp.live.com
Hotmail SMTP port: 25

**Comment by jedireza** [comment]
I'm not completely sure. Drywall uses [`emailjs`](https://github.com/eleith/emailjs), so if you can send an email with that, you'll surely be able to get it to work with Drywall.

[Frame](https://github.com/jedireza/frame) and [Aqua](https://github.com/jedireza/aqua) use [Nodemailer](https://github.com/andris9/Nodemailer).

Sorry again about the experience being bumpy because of email transport. I'm going to close the issue now since it doesn't seem like an issue with Drywall itself. Feel free to keep posting on this thread if you need help.

**Comment by harshalbagul-cse** [comment]
@jedireza I can send google mail by using Nodemailer. If i have to implement nodemailer insted of emailjs So what should I do ?
