### ISSUE TITLE
Google+ Social Login not Working

### ISSUE THREAD

**Issue by benmarten** [jedireza/drywall#298]
I have configured google plus login as described in the wiki.

Unfortunately it doesn't work completely. Signup and Login seems to work, but i'll just get redirected back to the login form....

My app is here: https://www.lohnanmeldung.de

Btw: Facebook Login works...

**Comment by jedireza** [comment]
Thanks for creating an issue.

I just tried this locally and got the same behavior. I traced out the error and saw this:

```bash
{
	'0': { [InternalOAuthError: failed to fetch user profile]
		name: 'InternalOAuthError',
		message: 'failed to fetch user profile',
		oauthError: {
			statusCode: 403,
			data: '{\n "error": {\n  "errors": [\n   {\n    "domain": "usageLimits",\n    "reason": "accessNotConfigured",\n    "message": "Access Not Configured. The API (Google+ API) is not enabled for your project. Please use the Google Developers Console to update your configuration.",\n    "extendedHelp": "https://console.developers.google.com"\n   }\n  ],\n  "code": 403,\n  "message": "Access Not Configured. The API (Google+ API) is not enabled for your project. Please use the Google Developers Console to update your configuration."\n }\n}\n'
		}
	}
}
```

Most useful information:

> Access Not Configured. The API (Google+ API) is not enabled for your project.

Here's what I did:

 - Go to https://console.developers.google.com
 - Selected my app
 - Went to the APIs & auth > APIs screen
 - Choose Social APIs > Google+ API 
 - Click enable API button

Then I tried again and all seems well. Can you confirm and then maybe we should update the wiki page if that works.

**Comment by benmarten** [comment]
Yes, indeed. That solved it! Thanks for your help!

**Comment by jedireza** [comment]
Great. I added a note to the wiki. Thanks for the help.
