### ISSUE TITLE
PageSpeed Insights Optimization & CacheBreaker

### ISSUE THREAD

**Issue by benmarten** [jedireza/drywall#299]
First of all thanks for this great project! 

I run your sample site (and my project of course ;) ) through Google's PageSpeed Insights Tool: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdrywall.herokuapp.com&tab=mobile

The tool identifies only three problems. Two of them ("Size content to viewport" & "Optimize images") are easy to fix.
Regarding the other issue I have a question: "Eliminate render-blocking JavaScript and CSS in above-the-fold content"
- What does the cacheBreaker in drywall's app.js actually do? (I searched the whole project + wiki, couldn't find anything...)
- To fix the page speed error, one could probably use: https://www.npmjs.com/package/grunt-penthouse . Or similar.... any thoughts?

**Comment by benmarten** [comment]
Update: In the meantime I managed to get it to 100% on Google PageSpeed Insights:  https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Flohnanmeldung.herokuapp.com%2F&tab=mobile

Let me know if that is something which is in scope of drywall and I could send a PR...

**Comment by jedireza** [comment]
Thanks for creating an issue. The `cacheBreaker` is a cheap way to force the browser to update css/js assets. Admittingly it's probably not a great long term solution and could probably be removed from Drywall.

Can you share the diff to get Drywall to 100% like you mentioned above?

**Comment by benmarten** [comment]
I've sent two PR's ;)

I don't think cacheBreaker value is changing automatically? is it?

**Comment by jedireza** [comment]
Cool. And no `cacheBreaker` doesn't change automatically.

**Comment by jedireza** [comment]
@benmarten is this issue still relevant since we closed #302?
