### ISSUE TITLE
FontAwesome Icons Issue on Safari

### ISSUE THREAD

**Issue by benmarten** [jedireza/drywall#300]
I noticed an issue on Safari with the FontAwesome icons. It is reproducible with Safari 8.0.6 and current drywall test page: http://drywall.herokuapp.com/login/

As you can see the Facebook Icon and Google+ Icon is not visible.
![screen shot 2015-06-23 at 12 31 46](https://cloud.githubusercontent.com/assets/5960238/8304226/857edc70-19a4-11e5-9c73-d3f485a13c89.png)

In Chrome and Firefox it's working, though.

**Comment by jedireza** [comment]
Thanks again for creating an issue and being involved in the project. :pray:

I opened it up in Safari and things seem to be working fine. Strange.

![screen shot 2015-06-24 at 3 52 30 pm](https://cloud.githubusercontent.com/assets/979929/8343361/476b3326-1a89-11e5-910e-445ab2b15452.png)

**Comment by benmarten** [comment]
Definitely! It's a great project, thanks for making it :)

Now, i tested it on another mac also, and it definitely. work, then found the root in my AdBlockPlus of safari (Fanboy's Annoyance List, was activated).

Thanks for testing it and sorry for the wrong report, should have thought of that before ;)

**Comment by jedireza** [comment]
No worries at all. Create issues for anything.
