### ISSUE TITLE
Socket.IO example not working

### ISSUE THREAD

**Issue by RobinKuiper** [jedireza/drywall#304]
Hi,

Yesterday I started implementing the Socket.io example into my Drywall setup.
I didn't work. Today I copy pasted the entire example into the right files. And it still doesn't work.

I don't get any errors. And the connection is good.
But it looks like he doesn't send sockets.

I can type in chat, and it says: "Me: {message}". But that's all, he doesn't even show to: "You joined the chat room message".

Any ideas?

**Comment by jedireza** [comment]
Thanks for creating an issue.

That tutorial was written a long time ago and I'm sure things have changed in socket.io since then. You may want to checkout their docs and see what's different. If you figure it out please update the wiki and/or share your results in this thread.
