### ISSUE TITLE
integrate another app into drywall

### ISSUE THREAD

**Issue by jskye** [jedireza/drywall#305]
im abit confused about how to integrate another app into drywall.
i thought the easiest way would be to try vhosts on diff subdomains. 
but im unsure exactly how to do this and was wondering if i could get any tips. ive tried [here](https://github.com/jskye/drywall/tree/vhost-login).

```
vhost = require('vhost');
var loginapp = exports.app = express();
//vhosts
loginapp.use(vhost('www.website.com', app)); // Serves top level domain via Main server app
loginapp.use(vhost('login.website.com', require('./pollsapp/app.js').app)); // Serves login subdomain via Redirect app

//listen up
loginapp.server.listen(app.config.port, function(){
  //and... we're live
  console.log('Server is running on port ' + config.port);
});
```

`Error: .get() requires callback functions but got a [object Undefined]`

**Comment by jedireza** [comment]
Thanks for creating an issue.

> im abit confused about how to integrate another app into drywall.

Drywall was built as a boilerplate/starter. You start with Drywall and build up on it. So I'm not sure if you're use case aligns with the intended use. I may be misinterpreting what you're going after so feel free to clarify your goals.

**Comment by jskye** [comment]
i have another MEAN app that should be the landing when the user is logged in. i was hoping to integrate the app in with the user management of drywall. this seemed to be a headache if i was trying to merge them in together (even if i wasnt a MEAN n00b). so i thought i could just use them on separate subdomains using the [vhost method](http://stackoverflow.com/questions/6866751/how-to-combine-two-node-js-app-server-together). But i guess i need to build a better understanding of the node server because im getting an error where callbacks are not found.

**Comment by jedireza** [comment]
I haven't used the vhosts method myself but in theory it should work. The error you're getting `Error: .get() requires callback functions but got a [object Undefined]` ... sounds like one of the express routes is defined incorrectly. That doesn't sounds like a conflict of using Drywall with vhosts.

Maybe you could try by starting with a [basic vhosts setup](https://github.com/strongloop/express/blob/master/examples/vhost/index.js), get that working and build it up from there.
