### ISSUE TITLE
Connecting an admin CRUD page to a data collection on MongoLab

### ISSUE THREAD

**Issue by bendtheji** [jedireza/drywall#307]
Hi jedireza,

Firstly, thank you so much for helping to solve my session timeout issue a few days ago, really helped me a lot :)

I have looked at the drywall wiki and looked at the admin CRUD wiki page and I get a good idea of setting up a simple admin CRUD, however I would like to enquire on how one might be able to connect to the MongoLab data collections. I have already added the MongoLab URI to the config file but I am unsure of where I should go to next. Is there any documentation that I should be reading up on? Hope to hear from you soon. 

Regards.

**Comment by sonicviz** [comment]
Hi,
http://stackskills.com/courses/learn-nodejs-by-building-10-projects has a module on exactly this topic:
MongoLab & Drywall Setup 

I did run into a bit of a showstopper issue which I'm about to post as another issue as it may save someone else the couple of hours headbanging it caused me!

**Comment by jedireza** [comment]
@bendtheji 

> Firstly, thank you so much for helping to solve my session timeout issue a few days ago, really helped me a lot :)

I'm glad that helped.

> ... however I would like to enquire on how one might be able to connect to the MongoLab data collections. I have already added the MongoLab URI to the config file but I am unsure of where I should go to next.

Do you mean how can you connect to MongoLab via the command line?

**Comment by jedireza** [comment]
@sonicviz thanks for sharing that link.

**Comment by bendtheji** [comment]
@sonicviz Thanks for the suggestion!

@jedireza Hi, here's an update on what's going on so far. I followed the admin CRUD wiki page again and this time we managed to clear up the confusion because we didn't realise the data collection that appears on MongoLab would be named in plural form. So yes, we managed to connect to the data collection. Thanks for replying!

I have another question though. We imported a data collection to our MongoLab account and now all of our documents have a random _id number value assigned to them, whereas when you add a document directly through the admin page, the _id attribute has a value of "pivot"-"name". I'm wondering if there is a way to change the existing random _id values in MongoLab?

**Comment by jedireza** [comment]
It doesn't look like you can change the `_id` property once set.
http://stackoverflow.com/a/4012997

I tested this on the command line:

```js
> db.foo.insert({ _id: 'space', name: 'race' });
WriteResult({ "nInserted" : 1 })

> db.foo.insert({ name: 'dynamo' });
WriteResult({ "nInserted" : 1 })

> db.foo.find()
{ "_id" : "space", "name" : "race" }
{ "_id" : ObjectId("559f64dad4251d755065302d"), "name" : "dynamo" }

> db.foo.update({_id: ObjectId("559f64dad4251d755065302d")}, {_id: 'custom'})
WriteResult({
        "nMatched" : 0,
        "nUpserted" : 0,
        "nModified" : 0,
        "writeError" : {
                "code" : 16837,
                "errmsg" : "The _id field cannot be changed from {_id: ObjectId('559f64dad4251d755065302d')} to {_id: \"custom\"}."
        }
})

> db.foo.find()
{ "_id" : "space", "name" : "race" }
{ "_id" : ObjectId("559f64dad4251d755065302d"), "name" : "dynamo" }
```
