### ISSUE TITLE
Drywall setup - HTTPS mail issue

### ISSUE THREAD

**Issue by sonicviz** [jedireza/drywall#308]
Hi,
I was testing out Drywall with MongoLab on Win 8.1 for the first time and ran into a brickwall at the password reset stage during setup.

No matter what SMTP (Gmail, Amazon SES, my own) I used I kept getting  "SMTPError 5 err: Error: self signed certificate in certificate chain" on my root email. The initial message was really cryptic, just something like sending error so I had to debug the response.js in EmailJS to get a pointer as to the real issue.

After much headbanging it turned out to be AVAST's new HTTPS scanning, which I had to uncheck in order to get the SMTP mailing to work correctly. I'd only recently dumped MSE for AVAST but it didn't click until I found a comment right at the bottom of https://github.com/npm/npm/issues/7439#issuecomment-76024878

So it's not just an AVAST issue, but general AV with their new HTTPS snooping..er, scanning features.

More info here:
http://security.stackexchange.com/questions/73476/why-is-avast-web-mail-shield-root-listed-as-ca-for-google-com

Not sure if this is a Drywall issue per se, but it took me a little while to figure out so maybe you could look into it or add a note to the setup docs to save someone else some pain.

ty for the cool tool!

**Comment by jedireza** [comment]
Thanks for creating an issue.

I'm not sure this it directly related to Drywall. And like you mentioned you had to debug [`emailjs`](https://github.com/eleith/emailjs) to realize what's causing the error. And then it may not be directly related to `emailjs` either. Admittedly I haven't used Windows in a long time and am unfamiliar with AV/AVAST/MSE and how those things play a role with this.

> ty for the cool tool!

You're welcome. :pray:

**Comment by sonicviz** [comment]
>>Admittedly I haven't used Windows in a long time and am unfamiliar with AV/AVAST/MSE and how those things play a role with this.

If you're developing platform agnostic tools you also need to test on those platforms under conditions that most people use. *most* people do use some form of AV, and https scanning is a recent addition to AV tools. At the very least you should add a note in the troubleshooting area of the install guide to help future users who may encounter similar confounding issues.

**Comment by jedireza** [comment]
@sonicviz would you be willing to help start the message you'd like to see in the install guide?

**Comment by sonicviz** [comment]
Issue:
When using an SMTP mail provide with HTTPS you may encounter the following error when trying to reset your password in the Drywall setup phase. 
Error: 'connection encountered an error'
This is fairly cryptic but if you debug response.js in EmailJS you will see the actual error is:
 "SMTPError 5 err: Error: self signed certificate in certificate chain"

Solution: 
Check if you are using an Antivirus solution like AVAST or Kaspersky that has HTTPS scanning enabled. Disable the HTTPS scanning in the AV program options and you should now be able to connect to your SMTP provider over HTTPS ok.
More info: http://security.stackexchange.com/questions/73476/why-is-avast-web-mail-shield-root-listed-as-ca-for-google-com

**Comment by jedireza** [comment]
:ok_hand: perfect! Thank you for this.

I added a new note under the requirements section in the README that links to the new wiki page: [Trouble sending email](https://github.com/jedireza/drywall/wiki/Trouble-sending-email).
