### ISSUE TITLE
How to achieve pagination logic with drywall?

### ISSUE THREAD

**Issue by tarekshumaila** [jedireza/drywall#309]
Hi Follks,

I am trying to figure out the last piece of puzzle in my project and I am kind of stuck. I am using drywall's pagedFind method to get the results that I want and limiting the results to 12 / page. Right now the results set are 17, so I know there are few left to be shown in the next page. The issues am having is finding a way to link to the next page so the remaining results will be displayed when someone click next page and ability to go to previous page.

I made a console.log(output); variable in pagedFind method and I am seeing the following variables:

pages: 
   { current: 1,
     prev: 0,
     hasPrev: false,
     next: 2,
     hasNext: true,
     total: 2 },
  items: { begin: 1, end: 12, total: 17 } }

looks good so far, but what should I include in the jade template to link the numbers together so I can see the next set of items? any help would be deeply appreciated.

Thanks in advance!

**Comment by tarekshumaila** [comment]
looks like I solve my own issue, wanted to share just incase someone needs help with this. I needed to pass the results.pages to my view from index.js:

else {
	  results.filters = req.query;
	  res.render('section', { data: results.data, page: results.pages }); <-- now you can access page vairable from jade template.
	  //console.log('results.data here ........');
	  console.log(results.pages);
	}

I did quite some work to achieve pagination logic on jade template. Also made it so it shortens the pages so that it will look pretty on mobile basically. Not the best piece of code that I have written, but it works:

nav
      ul.pagination
        if(page.hasPrev==false)
          li.disabled
            a(href="#" aria-label="Previous")
              span(aria-hidden="true") &laquo;
        else
          li
            a(href="/cars/?page=#{page.prev}" aria-label="Previous")
              span(aria-hidden="true") &laquo;
        if(page.current==1)
          - var n = 1
          while n < 6
            if(page.current==n)
              li.active
                a(href="/cars/?page=#{page.current}")=n++
            else
              li
                a(href="/cars/?page=#{n}")=n++
        if(page.current==2)
          - var n = 1
          while n < 6
            if(page.current==n)
              li.active
                a(href="/cars/?page=#{page.current}")=n++
            else
              li
                a(href="/cars/?page=#{n}")=n++
        if(page.current==3)
          - var n = 1
          while n < 6
            if(page.current==n)
              li.active
                a(href="/cars/?page=#{page.current}")=n++
            else
              li
                a(href="/cars/?page=#{n}")=n++
        if(page.current>3)
          - var n = page.current-2
          while n < page.current+3
            if(page.current==n)
              li.active
                a(href="/cars/?page=#{page.current}")=n++
            else
              li
                a(href="/cars/?page=#{n}")=n++
        if(page.total > 5)
          li.disabled
              a(href="/cars/?page=#{n}") ...
          li
              a(href="/cars/?page=#{n}")=page.total+1
        if(page.hasNext)
          li
            a(href="/cars/?page=#{page.next}" aria-label="Next")
              span(aria-hidden="true") &raquo;
        else
          li.disabled
            a(href="#" aria-label="Next")
              span(aria-hidden="true") &raquo;

I'll attach a picture so you can see how it looks. Cheers
![screen shot 2015-07-12 at 1 24 46 am](https://cloud.githubusercontent.com/assets/6101167/8636872/d3a78156-2834-11e5-930c-e344c68ddf97.png)

**Comment by jedireza** [comment]
Thanks for creating an issue. I'm glad you got it worked out.
