### ISSUE TITLE
html5shiv is not in the npm registry.

### ISSUE THREAD

**Issue by AdilAliMahin** [jedireza/drywall#312]
I'm trying to install drywall on my machine window 8.1. but when I run

```
npm install

1218 verbose statusCode 404
1219 verbose pkgid html5shiv
1220 verbose cwd F:\work\Jon Wash\drywallTest\drywall
1221 error Windows_NT 6.3.9600
1222 error argv "E:\\installed\\nodejs\\\\node.exe" "E:\\installed\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
1223 error node v0.12.7
1224 error npm  v2.11.3
1225 error code E404
1226 error 404 Registry returned 404 for GET on https://registry.npmjs.org/html5shiv
1226 error 404
1226 error 404 'html5shiv' is not in the npm registry.
1226 error 404 You should bug the author to publish it (or use the name yourself!)
1226 error 404 It was specified as a dependency of 'Drywall'
1226 error 404
1226 error 404 Note that you can also install from a
1226 error 404 tarball, folder, http url, or git url.
1227 verbose exit [ 1, true ]
```

**Comment by jedireza** [comment]
Thanks for creating an issue. This module seems to have been unpublished. For the time being, we can follow https://github.com/aFarkas/html5shiv/issues/163

**Comment by ahunter-bluemix** [comment]
I was not sure how to get around this issue by reading the referenced dependency bug.

In the end I solved the issue by running:
% npm install https://github.com/aFarkas/html5shiv.git --save
% npm install

**Comment by jedireza** [comment]
Yes it's a bummer that the module was unpublished and I hope it gets figured out soon.

**Comment by jedireza** [comment]
Looks like this got fixed and has been re-published to npm. Please report any issues you come across.
