### ISSUE TITLE
Session clean out from database

### ISSUE THREAD

**Issue by tarekshumaila** [jedireza/drywall#314]
Hi there,

Thanks for all the help before, drywall is greatly supported and I am proud to finish up my application using this awesome tool. While I was testing my application, I noticed my mongodb session table had about 6,400ish records, taking up lots of space. Since then, I have cleared up the session table to start over. Now, I am at 175 records in there. Is there a way to let drywall automatically clear up the sessions stored in the database when the user logs off?

I did some testing to see when the session gets stored and it gets store when a session doesn't exists in the client. If it exists and you logout, then login, it doesn't store a new one. Not sure how I got up to 6,400 records earlier.

Hopefully there is an easy fix for it, if not I will just clear them manually every now and then.

Thanks!
Tarek

**Comment by jedireza** [comment]
Thanks for opening an issue. `connect-mongo` is the module that's creating the sessions in Drywall. This section of their docs may be of help:

 - https://github.com/kcbanner/connect-mongo#remove-expired-sessions
