### ISSUE TITLE
Evite replacement?

### ISSUE THREAD

**Issue by benlower** [jedireza/drywall#316]
I'm looking for a way to host very lightweight event invitations (think Evite but without ads and all the bullshit).  Would drywall be viable for this scenario?  Are there any other projects you know of that might be a better fit for me?

Thanks for any pointers you can provide!

**Comment by jedireza** [comment]
Thanks for opening an issue.

> Would drywall be viable for this scenario?

It could. But these day's I'd reach for [Aqua](https://github.com/aqua/) over Drywall. It has tests and I prefer hapi+react over express+backbone. If you're looking for something without a front-end checkout [Frame](https://github.com/frame/).

> Are there any other projects you know of that might be a better fit for me?

As a turn-key solution with events+invites in mind... not that come to mind.

**Comment by benlower** [comment]
Thanks for the pointers
