### ISSUE TITLE
Updates in admin

### ISSUE THREAD

**Issue by LoicDagnas** [jedireza/drywall#318]
Hi,
first of all, I have used Drywall for three months and it is a very very great framework, thanks a lot!

However, I may have found a problem in the administration pages. For example if I want to update an account phone number:
* I modify the field phone number from `phone1` to `phone2`
* I click `update`
* I modify again the phone number from `phone2` to `phone3`
* I click `update` again and then `phone2` is displayed in the phone number  field instead of `phone3`

Of course it is just an example, the same strange thing could be seen for the other fields and the other models (user, admin-group...).

In my opinion, it is tied to the use of ` this.listenTo(app.mainView.model, 'change', this.syncUp);` in the Backbone model, I don't use this listener any more and it seems to work fine. 

Best

Loïc

**Comment by jedireza** [comment]
> first of all, I have used Drywall for three months and it is a very very great framework, thanks a lot!

Thanks! That's always nice to hear. Although it's not a framework :wink:, but as boilerplate.

> However, I may have found a problem in the administration pages...

I just tried these steps with the live demo and wasn't able to reproduce the bug.

**Comment by LoicDagnas** [comment]
I have cloned again the repository yesterday and reproduced the bug (in localhost).

But you are right, I am not able to reproduce it with the online demo.

**Comment by jedireza** [comment]
Hmm. If you can find the cause a PR would be great. :wink:

**Comment by jedireza** [comment]
I think I know why this is happening. Mongoose is returning the original document. In another project, I had to go through all my `findByIdAndUpdate` commands and add an `options` argument if one didn't exist or modify the current one to include `{ new: true }`, which will cause MongoDB to return the updated document instead.

See: http://mongoosejs.com/docs/api.html#model_Model.findByIdAndUpdate

**Comment by jedireza** [comment]
I think I know why this is happening. Mongoose is returning the original document. In another project, I had to go through all my `findByIdAndUpdate` commands and add an `options` argument if one didn't exist or modify the current one to include `{ new: true }`, which will cause MongoDB to return the updated document instead.

See: http://mongoosejs.com/docs/api.html#model_Model.findByIdAndUpdate
