### ISSUE TITLE
Heroku Drywall mongoDB 3.0

### ISSUE THREAD

**Issue by MrLeusk** [jedireza/drywall#320]
I have been using drywall. It was really awesome up until the scheduled mongodb upgrade to 3.0 on Sept 30. Now none of my app can run. I was contemplating restarting with a fresh version of drywall and making my app customizations again, but I don't see drywall.herokuapp.com running.

**Comment by kaleguy** [comment]
My installation of drywall is currently running on Heroku + Mongodb 3.0 with no problems, although I recently upgraded all of my node modules.

What errors are you getting in your log on startup on Heroku?

**Comment by jedireza** [comment]
Also IIRC, there is also a bug with Passport where some of the 3rd party strategies are not compatible with the latest local strategy.

**Comment by MrLeusk** [comment]
The deployment at https://drywall.herokuapp.com is getting an error.

**Comment by jedireza** [comment]
Correct. I need to update the mongodb drivers, among other things.

**Comment by jedireza** [comment]
The demo is running again. I didn't even have to update the MongoDB drivers. Just updated with master and redeployed and it was good.
