### ISSUE TITLE
Email Verification issue

### ISSUE THREAD

**Issue by Jonasyao** [jedireza/drywall#321]
Hi,
Gmail verification works on my local machine.

Anyway, it fails in the AWS. (both ssl and tsl)

Is there any solution? I have tried master/update-deps branch, both email.js or nodemail.js fail.

**Comment by Jonasyao** [comment]
Error Sending: Email failed to send. Error: authorization.failed

**Comment by Jonasyao** [comment]
Do I need to install anything on EC2?

**Comment by jedireza** [comment]
Thanks for opening an issue. Have you checked out these wiki pages?

 - https://github.com/jedireza/drywall/wiki/Trouble-sending-email
 - https://github.com/jedireza/drywall/wiki/Issues-using-Gmail-SMTP

**Comment by Jonasyao** [comment]
I figure out to use AWS simple email service. But in my email body, it is still "http://127.0.0.1:3001/login/".

what should I do? change attemptSchema.set('autoIndex', (app.get('env') === 'production'));?

**Comment by jedireza** [comment]
Yeah I've used AWS SES too.

The host name in the emails comes from `req.headers.host` as seen here:

 - [/views/account/verification/index.js#L11](https://github.com/jedireza/drywall/blob/ca35c06bf5100d2835da929bd1bd3c39ae441138/views/account/verification/index.js#L11)
 - [/views/signup/index.js#L145](https://github.com/jedireza/drywall/blob/ca35c06bf5100d2835da929bd1bd3c39ae441138/views/signup/index.js#L145)

**Comment by Jonasyao** [comment]
thx, but it seems it require email verification twice. also where is reset password host name setting?

**Comment by Jonasyao** [comment]
found the forgot...still wonder how to solve email verification twice issue. thx a lot

**Comment by Jonasyao** [comment]
fix
