### ISSUE TITLE
More than two roles to choose from?

### ISSUE THREAD

**Issue by bassie1995** [jedireza/drywall#324]
I've been looking in to Drywall to replace the current Passport setup with a more complete and tidier base for our app, but have a question about the roles.

I read that Strings are being used to have an 'either' option for two roles, but how do I extend that to three possible roles? 
A user can currently have one of three roles, so is it best to just give do 'admin', 'user' and 'moderator', for example?

Also, when extending, what would be the best option to have one user occupy multiple roles in this system?

Thanks in advance!

**Comment by bassie1995** [comment]
Oh, I see this has probably been replaced by 'canPlayRoleOf', right? I forgot about that. Woops!

**Comment by jedireza** [comment]
Thanks for creating an issue. Have you seen these wiki pages?

 - [Users, Roles & Groups](https://github.com/jedireza/drywall/wiki/Users%2C-Roles-%26-Groups)
 - [Admin & Admin Group Permissions](https://github.com/jedireza/drywall/wiki/Admin-%26-Admin-Group-Permissions)

**Comment by bassie1995** [comment]
Ah, right. I had forgotten to read them thoroughly. I should probably write those things down. Thanks!
