### ISSUE TITLE
SMTP Server Times Out

### ISSUE THREAD

**Issue by StephenMayeux** [jedireza/drywall#328]
I'm running a Node.js application on Cloud9 IDE, and I am stuck on the Drywall set up. I have followed your installation instructions on the README, but I am unable to reset the password. I'm storing my data on MongoLab, and interestingly enough, when I submit an email (on the Forgot Your Email? page) that's stored on db.users, then I get a timeout error. However, if I submit an email that isn't stored on the database, then I get a success message. Screenshots below:

Error message: This email is actually stored in db.users. After a few seconds, I get this error.

![error1](https://cloud.githubusercontent.com/assets/13535545/11468142/828ced12-9790-11e5-8908-8c8b48c7eeb5.png)

Success message: This is the message I see when I submit an email address that isn't stored in db.users

![error2](https://cloud.githubusercontent.com/assets/13535545/11468159/a2f9f798-9790-11e5-8abe-305082efddbe.png)

### More Context

1. Running a Node.js app on Cloud9 IDE
2. Drywall 0.16.4 installed
3. emailjs 0.3.16 installed
4. Have tried Outlook/Hotmail smtp and doesn't work.
5. Have tried iCloud/Me smtp and doesn't work
6. Have tried Google and read your documentation on the README
  * Have enabled my account to use less secure apps
  * have enabled two-step authentication and created an app specific password
  * have used said password in my config.js file (with the spaces included)
  * have tried both ssl and tls

Any help is appreciated and not taken for granted! If you need more information/context regarding my setup, please let me know.

**Comment by StephenMayeux** [comment]
Sorry to have wasted your time. It must be a problem with my gmail account. Tried the credentials here and it worked: http://stackoverflow.com/questions/30598980/emailjs-not-working-node-js

**Comment by jedireza** [comment]
:+1: Good stuff. Glad to hear you got it working.
