### ISSUE TITLE
Missing Google login and tumblr login

### ISSUE THREAD

**Issue by utkarshns** [jedireza/drywall#330]
Can't seem to find Google login and tumblr login in the sample:
https://drywall.herokuapp.com/signup/

In the features, they are listed:

**Comment by jedireza** [comment]
Thanks for creating an issue. Ensure that there are values present in your config:
https://github.com/jedireza/drywall/blob/ca35c06bf5100d2835da929bd1bd3c39ae441138/config.example.js#L42-L49

**Comment by utkarshns** [comment]
I didn't implement it yet, just tried the demo.
Couldn't find Google and time tumblr there.
If they work, this looks like a good solution.

**Comment by jedireza** [comment]
Yup. I don't have keys defined for google or tumblr on the live demo.
