### ISSUE TITLE
Building a "sub-user" system with drywall

### ISSUE THREAD

**Issue by dclxvi97** [jedireza/drywall#331]
I need to create a "sub-user" system. In the web application that I'm trying to create, its user can create a web application, so every user should be able to have its own user system. Is there any "natural" way to do so with drywall?

**Comment by jedireza** [comment]
Thanks for creating an issue. This has beened asked before, please see:

 - https://github.com/jedireza/drywall/issues/274
 - https://github.com/jedireza/drywall/issues/52

I hope this helps.
