### ISSUE TITLE
Compilation failed: bootstrap-vars.less not found 

### ISSUE THREAD

**Issue by amerdsp** [jedireza/drywall#337]
FYI - 

Compilation failed because of missing variable:  bootstrap-vars.less in the following files:

public/views/admin/categories/index.less
public/views/admin/statuses/index.less
public/views/index.less

I had to replace bootstrap-vars.less with bootstrap-build.less in the files above for it to compile.

**Comment by jedireza** [comment]
@garfbargle could you take a look?

**Comment by garfbargle** [comment]
Yes, shortly

**Comment by garfbargle** [comment]
@jedireza & @amerdsp 

Sorry for the issues guys. I'm am perplexed as to how my repo was working. I deleted my local repo, and cloned my fork to confirm the issue. I made the required updates in PR #338 for the fix. Again I deleted my local repo and tested that the new changes worked on a fresh clone.
