### ISSUE TITLE
Send mail by using Nodemailer

### ISSUE THREAD

**Issue by harshalbagul-cse** [jedireza/drywall#339]
As the many people face the problem to send mail via Gmail.
So I can send the mail via nodemailer, but Im unable to implement it in drywall.

Follow the steps.
1. Create Transport
var transporter = nodemailer.createTransport({
       service: 'Gmail',
       auth: {
           user: 'email@gmail.com',
           pass: 'password'
       }
   });
2.Assign Mailoption
   var mailOptions = {
       from: 'Company Name <email@gmail.com> ', // sender address
       to: 'Receiver Address', // list of receivers
       subject: 'Subject', // Subject line
       text: 'Mail Body', // plaintext body
   };
3.SendMail
   transporter.sendMail(mailOptions, function(error, info){
       if(error){
           return console.log(error);
       }
       console.log('Message sent: ' + info.response);
   });

**Comment by jedireza** [comment]
Nodemailer is good. We're using it with [Frame](https://github.com/jedireza/frame/).

You can swap out `emailjs` for `nodemailer` here:
https://github.com/jedireza/drywall/blob/master/util/sendmail/index.js

**Comment by harshalbagul-cse** [comment]
@jedireza Thanks for your help and support.

Following are steps to use nodemailer.

1.

//var emailjs = require('emailjs/email');
  var nodemailer = require('nodemailer');

2.
       //var emailer = emailjs.server.connect( req.app.config.smtp.credentials );
      //emailer.send({
      //  from: options.from,
      //  to: options.to,
      //  'reply-to': options.replyTo || options.from,
      //  cc: options.cc,
      //  bcc: options.bcc,
      //  subject: options.subject,
      //  text: options.text,
      //  attachment: attachments
      //}, function(err, message) {
      //  if (err) {
      //    options.error('Email failed to send. '+ err);
      //    return;
      //  }
      //  else {
      //    options.success(message);
      //    return;
      //  }
      //});

      var transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
          user: 'email@gmail.in',
          pass: 'password'
        }
      });

      var mailOptions = {
        from: options.from, // sender address
        to: options.to, // list of receivers
        subject: options.subject, // Subject line
        text: options.text, // plaintext body
      };

      transporter.sendMail(mailOptions, function(error, message){
        if (err) {
          options.error('Email failed to send. '+ err);
          return;
        }
        else {
          options.success(message);
          return;
        }
      });
    }
