### ISSUE TITLE
Why can't I log in?

### ISSUE THREAD

**Issue by amerdsp** [jedireza/drywall#340]
I have a script (below) to automate a login on a device.  The server is running drywall and functions with a browser just fine.

I keep getting ForbiddenError: invalid csrf token. 
```
'use strict';
var request = require('request');
var cookieJar = request.jar();
request = request.defaults({jar: cookieJar});
var baseURL = 'http://192.168.2.110:3000';

request(
  {
  url:  baseURL+'/login',
  method: 'GET',
  jar: cookieJar,
  followAllRedirects: true
  },
  function (error, httpResponse, body) {
    if(error) {
      console.error(error);
      return;
    }

  console.log(cookieJar);

  request(
  {
    method: 'POST',
    url: baseURL+'/login',
    contentType: 'application/json',
    form: {username:'user', password:'pass'},
    jar: cookieJar,
    followAllRedirects: true
  },
  function(error, httpResponse, body) {
    if(error) {
       console.error(error);
       return;
    }
  });
});
```
Why isn't the csrf token being passed properly?  

Thank you in advance.

**Comment by jedireza** [comment]
Thanks for opening an issue. The csrf token is sent to the client via a cookie and then sent back to the server via request headers. We do this on the client side here:

https://github.com/jedireza/drywall/blob/d6d6d7b1fb036f927a6cd3f5e6a1717683e50614/public/layouts/core.js#L16-L20
