### ISSUE TITLE
Email problem

### ISSUE THREAD

**Issue by kentyap** [jedireza/drywall#357]
I used email with dot. ie john.lam@gmail.com and it does not work  but when I change to johnlam@gmail.com without the dot it work.

Furthermore, you need to change security setting in the gmail account to accept connection via less secured devices.

**Comment by jedireza** [comment]
Thanks for opening an issue.

> I used email with dot. ie john.lam@gmail.com and it does not work but when I change to johnlam@gmail.com without the dot it work.

I'm not sure what you mean exactly. Where did you use this email? I just used the live demo and it seemed to work as expected.

> Furthermore, you need to change security setting in the gmail account to accept connection via less secured devices.

Again I'm not sure what you mean by this.

**Comment by kentyap** [comment]
What I mean is the string used for the email if it contains a dot between John and Lam it does not work.

and for for gmail account setting your need to disable this  https://www.google.com/settings/security/lesssecureapps

**Comment by benpoole** [comment]
Email addresses with dots in them work fine: I suspect something else was going awry for you.

**Comment by benpoole** [comment]
With regards Gmail, you should use 2-factor auth (as a general rule!) and if you do, you can also generate an app-specific password so you can use Gmail routing with your Drywall instance.

**Comment by jedireza** [comment]
Thanks @benpoole. @kentyap I'm closing this issue for now. Pleaes post here if you have a way we can reproduce the email address bug.
