### ISSUE TITLE
How to add required frontend (node) package?

### ISSUE THREAD

**Issue by hno2** [jedireza/drywall#358]
Sorry for the noob question!
But how can I add packages for Use in the Frontend?
E.g. add [Select2](https://www.npmjs.com/package/select2) to some pages.
Thanks in Advance for your answer!

**Comment by jedireza** [comment]
Thanks for opening an issue.

I'd suggest learning how our [`./Gruntfile.js`](https://github.com/jedireza/drywall/blob/520444296dd60e42702f793c181a53d2de15d98c/Gruntfile.js) bundles our client side code.

An alternative to bundling the code through the build system, you could also [include a script in the jade template](https://github.com/jedireza/drywall/blob/520444296dd60e42702f793c181a53d2de15d98c/views/admin/users/index.jade#L10).

**Comment by hno2** [comment]
Thanks very much for your answer
