### ISSUE TITLE
Favicon override

### ISSUE THREAD

**Issue by scottmont** [jedireza/drywall#359]
Hi,

I have been trying to override the favicon using serve-favicon and then defining my favicon.  I have search the project but can see where you are defining it.

My code

```js
    app.use(function(req, res, next) {
      if (req.get('Host').indexOf("id.carp.ca") > -1 ) {
        app.use(favicon(__dirname + '/public/media/carp/favicon.ico'));
          next();
      } else {
        app.use(favicon(__dirname + '/public/media/favicon.ico'));
        next();
      }
    });
```

**Comment by jedireza** [comment]
Thanks for opening an issue.

The `favicon.ico` file is located in the `./public/` directory. You could replace that file and not need `serve-favicon`. Or you could delete the `./public/favicon.ico` file and use that module.

The `./public` folder is being exposed using [`serve-static`](https://github.com/expressjs/serve-static) here: https://github.com/jedireza/drywall/blob/520444296dd60e42702f793c181a53d2de15d98c/app.js#L45

**Comment by scottmont** [comment]
Hi ,

Thank you for responding.  I have deleted that file but it continues to look for the public/favicon and ignores the module.

**Comment by jedireza** [comment]
I haven't used `serve-favicon` but you could also set the favicon with a `link` tag. You could use the hostname for that request as a template variable.

```html
<link rel="icon" type="image/png" href="path/to/favicon-hostname.png">
```

https://www.w3.org/2005/10/howto-favicon
