### ISSUE TITLE
Invalid request Error on Password Reset

### ISSUE THREAD

**Issue by costas90** [jedireza/drywall#361]
Hello,

Something goes wrong with my configuration I think.

First, when I tried to reset the password I got an error that the email failed to send, **even thought it was send.** I did receive the reset email.
![capture1](https://cloud.githubusercontent.com/assets/18027867/14409385/4a684fe8-ff1a-11e5-8a5f-36ee1a482945.PNG)

Then I get on the page to actually reset the password and I get the error "Invalid Request"
![capture](https://cloud.githubusercontent.com/assets/18027867/14409381/14f3b69a-ff1a-11e5-93fa-4d65f3cb350c.PNG)

In the `config.js` I use hotmail. I have added:

`    host: 'smtp-mail.outlook.com',
    tls: true,
    port: 587`

And I have enabled POP3 in my hotmail email settings.

Not sure what else to look for?

**Comment by costas90** [comment]
Its  abit strange but after disconnecting and then recoonecting, I clicked immediately on the link in the email to reset the password and the reset worked.

It seems that it doesnt work if I first enter my email to reset the password and then immediately click on the email link to change it.

**Comment by jedireza** [comment]
Thanks for opening an issue. So it seems like you got things working right?

**Comment by costas90** [comment]
Yes it does work just fine now. Not sure what went wrong back at that time.
