### ISSUE TITLE
Get data and display it?

### ISSUE THREAD

**Issue by keithsawkk** [jedireza/drywall#363]
Thank you for the drywall@@. Since i'm new for meanjs, I have lots of problem....

I can grunt and i would like to change some content which from mongodb and display it. But i really don't know how to do with drywall....

I created a new collection on mongoDB. And I need to display the data on the web page.

sorry i know it is very basic.. 

can you give a hand?? Thank you

**Comment by sturad** [comment]
I had my question on how to this the Drywall way, but these are things I've observed so far
@jedireza, I'm young in the force here. Please correct if any disinformation follows.

1. Create a Model class in the /schema/ directories using one of existing as model
1. Register this in /models.js
1. Build the server side controller for the screens in /views/<ModelNameOrWhatever/index.js
1 Define some routes for your screens in /routes.js
1. To flesh out the view,  define a jade page  /views/<ModelNameOrWhatever/index.jade
1. This is where I get fuzzy,
  - Your Jade template probably will have an underscore template that will get some handling from Backbone
  - Looking at /public/views/ for some examples on how to define Backbone Models and views
  - Backbone will form submit with AJAX.  In any case, you need to use AJAX POST to benefit from CSRF protection baked into Drywall.

**Comment by jedireza** [comment]
Thanks @sturad! You've defined this well.

> Your Jade template probably will have an underscore template that will get some handling from Backbone

I wish we didn't have to do this and this is one reason I created [https://github.com/jedireza/aqua/](Aqua), so I could use React from top to bottom. _Note: Aqua is out-of-date now and a PR was to update it, but needs to be completed._

These days I'd much rather start new projects using [Frame](https://github.com/jedireza/frame/). Frame is the heart of the Drywall API, but doesn't have a front-end. You have to build your own front-end.

@keithsawkk if you have more questions, please feel free to open new issues. :+1:

**Comment by sturad** [comment]
You're welcome @jedireza.  I'm glad I answered most of my own question.  Thanks for Drywall,  it's a good sign of structure on a system that it's possible to build a feature by following the layout of another one!  I get the pain points though. Looking forward to delving into Frame and Aqua, but meanwhile supporting Drywall in the wild.
