### ISSUE TITLE
Lock user information?

### ISSUE THREAD

**Issue by ruehri** [jedireza/drywall#364]
Hello jedireza,

First of all thanks a lot for this great project, it is a fantastic code base that helps us all in setting up a user system.

I would like to check if there is some easy way to prevent user information from getting overwritten, such as for public accounts. There are surely lots of ways in preventing that, but just wanted to check if there was some build-in way that I have not discovered yet.

Thanks a lot in advance!

**Comment by jedireza** [comment]
Thanks for creating an issue.

> First of all thanks a lot for this great project, it is a fantastic code base that helps us all in setting up a user system.

Thank you.

> I would like to check if there is some easy way to prevent user information from getting overwritten, such as for public accounts. There are surely lots of ways in preventing that, but just wanted to check if there was some build-in way that I have not discovered yet.

Nothing built-in no. I'm curious though. Would you be willing to share an example of what you mean?
