### ISSUE TITLE
Incorporate drywall in existing node SPA

### ISSUE THREAD

**Issue by utkarshns** [jedireza/drywall#365]
**Objective**:
I want to integrate my [website dashboard](https://wrapbootstrap.com/theme/inspinia-responsive-admin-theme-WB0R5L90S) with drywall.

**Scenario**:
Our dashboard SPA is built on node + express + angular + embeddedjs + mongoDB.
We use the command `grunt live' to run the  dashboard SPA.

**Our code**:
**[https://github.com/webFaclon/faclon_website](https://github.com/webFaclon/faclon_website)**

**Problems**:
**1**:
How to integrate drywall in our dashboard SPA and run both on one server alongside MongoDB.

**2**:
The dashboard SPA uses embeddedJS as the view model whereas, drywall uses Jade (pug), will there be any conflicts? or this would work > [Stackoverflow: Using multiple view engines](http://stackoverflow.com/questions/15063262/is-there-any-way-to-use-multiple-view-engines-with-express-node-js)

**Comment by lmessinger** [comment]
+1 I'm wondering if you could suggest what components can be wrapped in angular directives (if att all). thanks!

**Comment by jedireza** [comment]
Thanks for opening an issue. Here are a couple relevant issues:

> Drywall was built as a boilerplate/starter. You start with Drywall and build up on it. So I'm not sure if you're use case aligns with the intended use. I may be misinterpreting what you're going after so feel free to clarify your goals.

Via: https://github.com/jedireza/drywall/issues/305

> I haven't used Angular myself. [Frame](https://github.com/jedireza/frame) is the core Drywall API using Hapi instead of Express. I know that @Silom was working on creating an Angular front-end to it. https://github.com/Silom/ngFrame

Via: https://github.com/jedireza/drywall/issues/290

- - - -

> 1: How to integrate drywall in our dashboard SPA and run both on one server alongside MongoDB.

This isn't impossible, you do have to do the work merging the two projects together though. There isn't a general-solution/best-practice here.

> 2: The dashboard SPA uses embeddedJS as the view model whereas, drywall uses Jade (pug), will there be any conflicts? or this would work > Stackoverflow: Using multiple view engines

Although I don't typically have two template engines in a project, I'm sure there are ways to accomplish this. Again, comes down to finding a solution you feel good maintaining.

- - - - -

> +1 I'm wondering if you could suggest what components can be wrapped in angular directives (if att all). thanks!

I don't use Angular myself. It may be worth checking out https://github.com/Silom/ngFrame

**Comment by deksden** [comment]
Check this project: https://github.com/arthurkao/angular-drywall

This is fork of Drywall
