### ISSUE TITLE
How to create new screens?

### ISSUE THREAD

**Issue by sturad** [jedireza/drywall#366]
Question. I was wondering the best way to create an altogether new screen in Drywall that will work with all the layers of this stack.  It seems like there are a few touch point across the different layers and it's worth documenting.  I recently did this and found it easy enough to augment the User schema and save a field back on the model.  A couple things I'm still wondering about:
1. Considerations, should and how should you set up a Backbone view and/or model?
2. How should be one be adjusting Grunt tasks so that assets are built?

**Comment by jedireza** [comment]
Thanks for opening an issue.

I think you defined a lot of this well in #363. When I want to create a new screen or section, I generally just copy what already exists and customize to fit the new need. WIth Grunt I do the same. I hope this helps.
