### ISSUE TITLE
Use of const in strict mode when Running app

### ISSUE THREAD

**Issue by Damneo** [jedireza/drywall#367]
Hi,

when trying running the app, I get this error :

/drywall/node_modules/connect-mongo/src/index.js:3
    const Promise = require('bluebird');
    ^^^^^
    SyntaxError: Use of const in strict mode.

Using Node v0.12.0
Using npm 3.8.6

**Comment by Damneo** [comment]
Sorry, issue already posted with solution : https://github.com/jedireza/drywall/issues/353
I'm not pretty familiar with issues yet :)

**Comment by jedireza** [comment]
Thanks for opening an issue. I'm glad you got it worked out.
