### ISSUE TITLE
Host the App in a Server

### ISSUE THREAD

**Issue by jonavon7** [jedireza/drywall#368]
Hi!

I have the App (customized) running in my system perfectly and I wanted to host it in a server in cPanel. How it should be done and configured?

Right now I am working in the App running the terminal beforehand.

Cheers!

**Comment by jedireza** [comment]
Thanks for opening an issue. I haven't used cPanel myself so I'm not sure. But running Drywall should be like running most node/express apps.

 - https://www.google.com/search?q=node+cpanel
 - https://www.google.com/search?q=express.js+cpanel
