### ISSUE TITLE
Support for ejs templating

### ISSUE THREAD

**Issue by otusweb** [jedireza/drywall#369]
I'm using ejs for my templating engine and the fact that drywall used jade kept me from using it. Would be awesome if templates were provided for ejs too.

**Comment by jedireza** [comment]
Thanks for opening an issue. Template engine camps (and database camps, et al.) are impossible to please.

I suggest taking a look at [Frame](https://github.com/jedireza/frame/). It's the heart of the Drywall API written in Hapi (with tests 😉). The best part is the front-end is not included.
