### ISSUE TITLE
integrate drywall with my own project

### ISSUE THREAD

**Issue by s8mlu** [jedireza/drywall#370]
This project is great and has almost everything I need, but I'm wondering what's the best practice to leverage it in my own project. 

For example, let's say I have a plain vanilla "hello world" NodeJS project with it's own app.js, and now I want to add drywall user management features. I can certainly just modify the drywall app.js files and merge my code into it, but then I won't be able to easily get updates/fixes from this project using 'git pull' anymore. Ideally I would like to have 2 separate GIT repo, one for dryall and one for my own project. Is that the right way to go?

Thanks.

**Comment by jedireza** [comment]
Thanks for opening an issue. Boilerplates (like Drywall) are typically just starting points and you don't usually get updates.

**Comment by s8mlu** [comment]
Understood. It would have been great if I could include (or reference) Drywall as a "package" somehow in my own project so I can continue to take advantage of any new features or bug fixes that are made to Drywall in the future.

**Comment by jedireza** [comment]
Yes, that would be awesome. It's just not the nature of how boilerplates work.
