### ISSUE TITLE
IE 8,9 /login/reset redirects back to home

### ISSUE THREAD

**Issue by sturad** [jedireza/drywall#372]
1. User visits /login/forget and puts in their email.
2. User receives the tokened email and navigates to the reset page /login/reset
3. Reset page renders, but within moments user redirected to / 

I saw this behavior on drywall.herokuapp.com and also on a fork we have have Drywall.  It was on Internet Explorer 11 emulating 8 or 9 in Developer Tools which itself might not be the best scenario.  I will try to test later directly on one of those Internet Explorer.

**Comment by sturad** [comment]
The redirect m may  have something to do with Backbone.Router and pushState not working on IE <=9  In our case, this patch stops the redirect to /

-    Backbone.history.start({ pushState: true });
+    var enablePushState = true;  
+    var pushStateEnabled = !!(enablePushState && window.history && window.history.pushState);
+    Backbone.history.start({ pushState: pushStateEnabled });

**Comment by jedireza** [comment]
I'm not sure about how long support for IE8 will last. For example, in [Bootstrap 4 they're dropping support for IE8](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/).

Also this may be relevant: https://github.com/jashkenas/backbone/issues/173

**Comment by sturad** [comment]
As it turned out, we dropped support for IE <=10 so this became a non-issue for us.

**Comment by jedireza** [comment]
Ok. Closing for now.
