### ISSUE TITLE
Social Network Logins

### ISSUE THREAD

**Issue by artforlife** [jedireza/drywall#373]
Are these supposed to work out-of-the-box? Is additional setup needed? I am seeing buttons for FB and Twitter on the demo, but they do not show on my local version when I do a basic install.

**Comment by sturad** [comment]
Not out of the box.  you have to set some credentials.  I think this details it pretty well:  https://github.com/jedireza/drywall/wiki/Configuring-Social-Sign-Up-%26-Sign-In

**Comment by jedireza** [comment]
@artforlife thanks for opening an issue. And thanks @sturad for answering.

In summary, you need to enter the api credentials in the config file for the buttons to show up.
