### ISSUE TITLE
Account verification email.

### ISSUE THREAD

**Issue by subasnet** [jedireza/drywall#374]
Right now, the user is receiving only confirmation email while registering but is it possible to send account verification email while signing up?

**Comment by jedireza** [comment]
Thanks for opening an issue. I'm not sure I follow. What is the difference between registering and signing up?

**Comment by subasnet** [comment]
I have installed the app normally without any error. Right now when a user sign up he/she gets an email just as notification that his/her account has been created but I want the user to get email with a verification link to verify his/her account. So, it would be great to get some hints to do this. Thank you.

**Comment by jedireza** [comment]
You can set the config setting `requireAccountVerification` to `true`. 

https://github.com/jedireza/drywall/blob/cbd7cf31abb37503e00c39040e1952b65e6aac0b/config.example.js#L16

**Comment by jedireza** [comment]
Also this is relevant: https://github.com/jedireza/drywall/wiki/Added-Email-Verification-with-Social-Sign-Up

**Comment by subasnet** [comment]
Thankyo very much, now Its working.
