### ISSUE TITLE
Fetching additional fields from User records

### ISSUE THREAD

**Issue by MarkNixon** [jedireza/drywall#376]
Hi, thank you very much for this starter package, it's exactly what I needed for a project, and for self-learning. But I'm new to client-side Node development and I must be missing some obvious step to fetching additional data from Mongo. 

If I wanted to get "**resetPasswordExpires**" from "**users**" and display to the table on Users admin page, what are the steps involved, which files need to be updated?

I've updated _app.Record_ in _public\views\admin\users\index.js_:

```js
app.Record = Backbone.Model.extend({
    idAttribute: '_id',
    defaults: {
        _id: undefined,
        username: '',
        email: '',
        isActive: '',
        resetPasswordExpires: ''
    },
    url: function() {
        return '/admin/users/'+ (this.isNew() ? '' : this.id +'/');
    }
});
```

Don't need to update Schema because **resetPasswordExpires** is already there.

Updated the Jade template:
```
script(type='text/template', id='tmpl-results-table')
        table.table.table-striped
            thead
                tr
                    th
                    th username
                    th.stretch email
                    th active
                    th id
                    th expires
            tbody#results-rows

    script(type='text/template', id='tmpl-results-row')
        td
            input.btn.btn-default.btn-sm.btn-details(type='button', value='Edit')
        td <%= username %>
        td <%= email %>
        td <%= isActive %>
        td <%= _id %>
        td <%= resetPasswordExpires %>
````

Also, I know that this field exists and is populated, this is the data in MongoDB:
_"resetPasswordExpires" : "5/14/16 10:58:04 PM UTC"_ 

But when I compile and run, **username**, **email**, **isActive** and **_id** all are fetched, but **resetPasswordExpires** is blank, the connection to that particular field is still missing.

If anyone can help out I'd really appreciate! Thank you.

**Comment by jedireza** [comment]
Thanks for opening an issue. There is a `syncUp` function in some/most the views to keep in mind. In this case it's the `IdentityView` here:

https://github.com/jedireza/drywall/blob/cbd7cf31abb37503e00c39040e1952b65e6aac0b/public/views/admin/users/details.js#L121-L128

This `syncUp` method should be updated to include that `resetPasswordExpires` field.

```js
    syncUp: function() {
      this.model.set({
        _id: app.mainView.model.id,
        isActive: app.mainView.model.get('isActive'),
        username: app.mainView.model.get('username'),
        email: app.mainView.model.get('email'),
        resetPasswordExpires: app.mainView.model.get('resetPasswordExpires')
      });
    },
```

**Comment by MarkNixon** [comment]
Thanks!
