### ISSUE TITLE
how to host this on heroku

### ISSUE THREAD

**Issue by WooRanker** [jedireza/drywall#377]
I tried many times to deploy this on heroku but all times failed. app working on localhost without any issue. Please help me.

**Comment by jedireza** [comment]
Thanks for opening an issue. Have you revied the wiki page?

https://github.com/jedireza/drywall/wiki/Deploying-to-Heroku

**Comment by WooRanker** [comment]
thank you now, I'm trying it. `rm .gitignore` not working on my windows. what can i do for that?

**Comment by jedireza** [comment]
```bash
$ rm .gitignore
```

Is just deleting the `.gitignore` file.

**Comment by WooRanker** [comment]
thank you. in this line `heroku addons:add mongolab`

getting this error 

> C:\Users\Dinuka\Desktop\weCreate>heroku addons:add mongolab
WARNING: `heroku addons:add` has been deprecated. Please use `heroku addons:crea
te` instead.
 !    No app specified.
 !    Run this command from an app folder or specify which app to use with --app
 APP.

please help me i'm a noob with this. I already installed node and configured mongodb on localhost. everything working correct on localhost i just want deploy that to heroku.

thank you.

**Comment by jedireza** [comment]
You should refer to the `heroku` docs as I don't use windows.

**Comment by WooRanker** [comment]
ok do you can explain me this. now i installed node , configured mongodb details in the app and customized on localhost. what i have to do additional things to deploy this app to heroku.

do i need this lines  ?

`heroku addons:add mongolab
 npm install
 npm install grunt-cli -g
 mv config.example.js config.js
`

**Comment by jedireza** [comment]
You'll likely need `heroku addons:add mongolab` but the next 3 lines you mentioned are to install depenedencies locally and setup the config file.
