### ISSUE TITLE
How to access login context from my own app?

### ISSUE THREAD

**Issue by ajmas** [jedireza/drywall#381]
Should I be running drywall as its own node server or in the same process as my express application? Also, how should I get the login context to be used in my express application? 

BTW It would be useful to have a few examples, either in the wiki or source, on how to integrate drywall with a developer's own application.

**Comment by jedireza** [comment]
Thanks for opening an issue. This has been asked before.

From #365 

> Drywall was built as a boilerplate/starter. You start with Drywall and build up on it. So I'm not sure if you're use case aligns with the intended use. I may be misinterpreting what you're going after so feel free to clarify your goals.

Via: https://github.com/jedireza/drywall/issues/305
