### ISSUE TITLE
Can't insert long characters in input fields 

### ISSUE THREAD

**Issue by sanjaya-jay** [jedireza/drywall#382]
when trying to insert some long words in input fields it getting error like this

`MongoError: exception: Btree::insert: key too large to index, failing drywall.accounts`

how i can fix this ?

**Comment by jedireza** [comment]
Thanks for opening an issue. I haven't seen this before myself.

Maybe [this search](https://www.google.com/search?q=mongoError:+exception:+Btree::insert:+key+too+large+to+index) or [this StackOverflow answer](http://stackoverflow.com/questions/27792706/cannot-create-index-in-mongodb-key-too-large-to-index) could help.
