### ISSUE TITLE
importing

### ISSUE THREAD

**Issue by scottmont** [jedireza/drywall#384]
Hi,

Do you have any facility for importing users from a csv?

Thanks

**Comment by scottmont** [comment]
I have this so far. http://pastebin.com/yBzvZPht

Just have an issue updating the user schema with the account._id.

Any advice?

**Comment by jedireza** [comment]
Thanks for opening an issue.

> Do you have any facility for importing users from a csv?

Nope. What you have there seems reasonable. If this is a one-time thing then any throw-away solution should be sufficient.

I did notice that you're defining the schemas in that script instead of requiring them. Besides that you seem to be on the right track.

**Comment by scottmont** [comment]
just one last thing I can't seem to update the user schema with the account_id.

in drywall you use this 

      workflow.user.roles.account = account._id;
      workflow.user.save(function(err, user) {

I am unable to replicate that.  

Thank you !
