### ISSUE TITLE
Explanation of Directory Structure

### ISSUE THREAD

**Issue by davik** [jedireza/drywall#385]
Hello, 
I am using drywall for user management for a health-care project. But I am confused with the directory structure. Specifically I want to know the difference between "/public/layouts" and "/layouts", again "/public/views" and "/views".

**Comment by scottmont** [comment]
This is how i see it

public/views is client side , like the javascript on a page form
views/ is server side, like the javascript handling the login and db updates

same goes for the layouts ..some work is done server side including default css ,footers, headers for the site and some work is done client side like how the page will be rendered with client data.

**Comment by jedireza** [comment]
Thanks for opening an issue @davik. I think @scottmont said it well. Let us know if you have more questions.

**Comment by davik** [comment]
Thank you very much!!
