### ISSUE TITLE
grunt error

### ISSUE THREAD

**Issue by jeremycardona** [jedireza/drywall#387]
When I start i get this warning....

```
Aborted due to warnings.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! Drywall@0.18.0 start: `grunt`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the Drywall@0.18.0 start script 'grunt'.
npm ERR! This is most likely a problem with the Drywall package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Drywall
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls Drywall
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jerem\Documents\programming folders\events\npm-debug.log
```

**Comment by jedireza** [comment]
Thanks for opening an issue. I did some searching and found a similar issue over here: https://github.com/bitpay/insight-ui/issues/559#issuecomment-64117343

I do wonder if any of this has been resolved in the newer versions of npm and node. Would you be willing to try using the latest stable versions (`node@6.x`, `npm@3.x`)?

**Comment by jeremycardona** [comment]
:( no good, i update node to v6.2.1 and npm to v3.9.3  
also instead of using the zip I cloned it from git and reinstalled all the packages
Now I get this error 
Running "concurrent:dev" (concurrent) task
    Running "nodemon:dev" (nodemon) task
    Running "watch" task
    Waiting...
    [nodemon] 1.9.2
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: *.*
    [nodemon] starting `node app.js`
    Fatal error: spawn cmd ENOENT
Warning:  Use --force to continue.

Aborted due to warnings.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! Drywall@0.18.0 start: `grunt`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the Drywall@0.18.0 start script 'grunt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Drywall package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Drywall
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Drywall
npm ERR! There is likely additional logging output above.


maybe I should throw away my pc? haha

**Comment by jedireza** [comment]
Darn. Could you share more details about your environment? You can run `$ npm version` post the results here.

**Comment by jeremycardona** [comment]
{ npm: '3.9.3',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.2.1',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.52',
  zlib: '1.2.8' }

**Comment by YasharF** [comment]
@jeremycardona can you verify that C:\Windows\System32\ is still in the PATH Environment variable, and if not add it?

**Comment by jeremycardona** [comment]
Thanks a lot.

**Comment by jedireza** [comment]
Great news thanks @YasharF 🎉
