### ISSUE TITLE
Project File/Folder Layout

### ISSUE THREAD

**Issue by atonb117** [jedireza/drywall#389]
Hey, @jedireza.  Great tool. A couple questions.

Been learning Express for a year or so along with a couple of front end frameworks/libraries.  This is the first backbone project that I'm really getting a chance to dig into.

What's up with the folder structure of the project?  Is it "Backbone" thing?  I've done a lot of tutorials but this is the first time I've seen project structure like this.  Do you have any tips or ideas on how files and folders can be consolidated, for example, to reduce duplicity in file names to simplify development?

Also.  You were leaning towards Ampersand in #268 to update the frontend.  It seems like Ampersand is the spiritual successor to Backbone.  Do you have any comments, pointers, opinions, on refactoring Drywall to use Ampersand?

~~Lastly, this [course](https://www.eduonix.com/courses/Web-Development/Learn-Nodejs-by-building-10-Projects-From-Scratch) has an entire module dedicated to Drywall.  It's kinda dated, but it's very thorough and I was able to get all the functionality working (except for delete events).  Might want to add it as a training resources if it's not already listed there.~~ Creator of course already left issue (#351).

**Comment by jedireza** [comment]
Thanks for opening an issue.

> What's up with the folder structure of the project?

Just legacy structure from 4ish years ago. I'd probably structure it differently today if I were to refactor everything. I'd definitely separate the front and back ends more like I did in [Aqua](https://github.com/jedireza/aqua/).

> Do you have any comments, pointers, opinions, on refactoring Drywall to use Ampersand?

Not really, no.

- - - -

I hope that helps.
