### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ofirattia** [jedireza/drywall#390]
I have few questions about the logic of the user managment.
1. what is the reason that you decide to create Admins OR Accounts?
2. How you belong Users to specific Group?
3. Why you add Admin to group if he admin ? because he see everyone.
4. Account is regular user? if yes, why you dont let Account to be in Group?
5. There is Group Admins? that see only their scope? only the "Account\User" that belong to their group?

**Comment by jedireza** [comment]
Thanks for opening an issue.

> 1. what is the reason that you decide to create Admins OR Accounts?

Via: https://github.com/jedireza/drywall/wiki/Users%2C-Roles-%26-Groups#roles-accounts-admins--custom

> __Why are roles separate from Users?__ For sanity really. Did you realize that both Admins and Accounts are indeed Users? Both of them need to login, both of them can forget their passwords and have them reset. Storing user information on both the Account and Admin schemas would complicate the login logic, forcing us to overly abstract it or even duplicate it by creating two separate login screens.

> 2. How you belong Users to specific Group?

Users don't have a grouping function, but admins do. See https://github.com/jedireza/drywall/wiki/Users%2C-Roles-%26-Groups#roles--vs--groups

> 3. Why you add Admin to group if he admin ? because he see everyone.

I think the wiki speaks to this in detail. See https://github.com/jedireza/drywall/wiki/Admin-%26-Admin-Group-Permissions

> 4. Account is regular user? if yes, why you dont let Account to be in Group?

Via: https://github.com/jedireza/drywall/wiki/Users,-Roles-&-Groups#roles--vs--groups

> __Can I use groups with Accounts?__ Sure. Your project might benefit by extending Accounts with an AccountGroup schema (and permissions). For example, if I built a message board or wiki and I wanted some Accounts to moderate other Accounts or change site content... groups would be the perfect solution. It would be a huge overkill to create a new roll (and schema) for a Moderator, which is like an Account in every way, only differing by a permission.

> 5. There is Group Admins? that see only their scope? only the "Account\User" that belong to their group?

There are not rules to what people can see. Using roles and permissions you can create whatever combinations you'd like. See https://github.com/jedireza/drywall/wiki/Admin-%26-Admin-Group-Permissions
