### ISSUE TITLE
Request for a short wiki on how Drywall can be integrated with Android

### ISSUE THREAD

**Issue by davik** [jedireza/drywall#391]
Drywall is perfectly working for web based app, if I want to use the webservice from an Android or iOS app, how do I proceed?

**Comment by jedireza** [comment]
Thanks for opening an issue. #383 had a similar question.

My answer there is essentially the same:

> [...] You could customize the API to support mobile/desktop app clients, but those decisions aren't baked in. I also suggest checking out [Frame](https://github.com/jedireza/frame/), which is the Drywall API, built with hapi instead of express, has much better testing and doesn't come with all the front-end stuff.

**Comment by davik** [comment]
Thank you! Frame is awesome!
