### ISSUE TITLE
Email not sending

### ISSUE THREAD

**Issue by mylastore** [jedireza/drywall#392]
Initial reset password, not sending email. Using Mac most recent OS. I get this on the web console but never received the reset email. 

{success: false, errors: [], errfor: {}, email: "mrtonyq@me.com"}
email: "mrtonyq@me.com"
errfor
![screen shot 2016-06-28 at 10 31 54 pm](https://cloud.githubusercontent.com/assets/8906338/16441564/746e0eb4-3d80-11e6-81fd-e732a4458752.png)

:{}
errors
:
[]
success
:
false

**Comment by jedireza** [comment]
Sending email is all about your SMTP settings.

 - https://github.com/jedireza/drywall/wiki/Trouble-sending-email
 - https://github.com/jedireza/drywall/wiki/Issues-using-Gmail-SMTP

You could also try to `console.log` the error here: https://github.com/jedireza/drywall/blob/cbd7cf31abb37503e00c39040e1952b65e6aac0b/util/sendmail/index.js#L84
