### ISSUE TITLE
Cannot access Admin page

### ISSUE THREAD

**Issue by jazzkonnen** [jedireza/drywall#394]
Once i put my email into the forgot form, no email shows up. I've changed the json file, and receive emails when creating regular accounts.

**Comment by jedireza** [comment]
Thanks for opening an issue.

Make sure your email root user email address is correct and doesn't have any spaces. Also check your spam folder.

If you receive emails from the system for other things (like registration or contact form) there's no reason why you wouldn't receive them for forgot password.

**Comment by jazzkonnen** [comment]
All that is correct nothing goes to spam. When i check the database nothing goes into the user collection. And admin just adds
 {
    "_id": {
        "$oid": "577d12d259e8412f1b052f22"
    },
    "name": {
        "first": "Root",
        "last": "Admin",
        "full": "Root Admin"
    },
    "groups": [
        "root"
    ]
}

**Comment by jazzkonnen** [comment]
db.admingroups.insert({ _id: 'root', name: 'Root' });
db.admins.insert({ name: {first: 'Root', last: 'Admin', full: 'Root Admin'}, groups: ['root'] });
var rootAdmin = db.admins.findOne();
db.users.save({ username: 'root', isActive: 'yes', email: ‘jazz@pixod.com’, roles: {admin: rootAdmin._id} });
var rootUser = db.users.findOne();
rootAdmin.user = { id: rootUser._id, name: rootUser.username };
db.admins.save(rootAdmin);

**Comment by jedireza** [comment]
> When i check the database nothing goes into the user collection.

That seems like the root cause.

**Comment by jazzkonnen** [comment]
meaning i should do what?

**Comment by jedireza** [comment]
If you can't add records to the `users` collection, I'm not sure what could cause that. I'd assume there would be an error when you tried running this on your MongoDB cli:

```
> db.users.save({ username: 'root', isActive: 'yes', email: ‘****@pixod.com’, roles: {admin: rootAdmin._id} });
```

Also it's always helpful to mention some other details like:

 - operating system
 - version of MongoDB
 - version of node/npm

**Comment by jazzkonnen** [comment]
OS X 10.11
MongoDB shell version: 3.2.7
node v4.4.7

this is the error i get : 
2016-07-06T17:13:04.101-0400 E QUERY    [thread1] SyntaxError: illegal character @(shell):1:84

2016-07-06T17:13:04.126-0400 I NETWORK  [thread1] Socket recv() errno:54 Connection reset by peer 107.22.52.32:21000
2016-07-06T17:13:04.163-0400 I NETWORK  [thread1] SocketException: remote: (NONE):0 error: 9001 socket exception [RECV_ERROR] server [107.22.52.32:21000]

**Comment by jedireza** [comment]
Interesting, your query seems to be using different ticks for the email address field `‘` and `’`. Replace those with `'` and give it a try.

**Comment by jazzkonnen** [comment]
Thank you the help is much appreciated. Also thank you for building this, can't wait to get started now.

**Comment by jedireza** [comment]
Yay! I'm glad we figured it out.
