### ISSUE TITLE
Question about Cache-Breaker

### ISSUE THREAD

**Issue by hno2** [jedireza/drywall#395]
Hey, 
thank for your awesome project. Helps me a lot getting started.
I have some questions about the Cache-Breaker:
Why is it needed?
And how do I disable it for using it in a production system?

Also do you have any other things to do that you think are necessary before using drywall in production?
Thanks in advance for you help

**Comment by jedireza** [comment]
> Why is it needed?

Sometimes browsers will cache assets (css/js) and an easy way to break that is by appending a unique query parameter to those paths. It's actually a pretty ugly solution that I implemented a long, long time ago.

> And how do I disable it for using it in a production system?

This is actually where you'd wan't something like this. You'd want to be certain that your end users are getting the most updated versions of the assets. The are better ways of doing this. One I just found by searching is [`grunt-cache-bust`](https://github.com/hollandben/grunt-cache-bust).

> Also do you have any other things to do that you think are necessary before using drywall in production?

Be sure to checkout [Frame](https://github.com/jedireza/frame/), it's the guts of Drywall, but without a front-end, and it has good test coverage. It's what I'd reach for today most likely.
