### ISSUE TITLE
Guide to inserting a new collection into schema?

### ISSUE THREAD

**Issue by SHBelsky** [jedireza/drywall#396]
I've looked at the documentation, and there isn't a good guide for inserting a new collection into the schema so that it is accessible to the rest of the site and API. For example, if I wanted to add a "Video" collection and be able to manage it from the administrator panel (in the same way that you can manage Categories and Statuses). I've done the following so far:

1. Copied the `views/admin/statuses/` folder to `views/admin/videos/`, and changed all references of "status" to "video" (similarly, "statuses" becomes "videos"). This breaks my CSS and JavaScript; I'm not sure where I should go to add my "Video" page to the list of pages that need to have a minified CSS and JS file.

2. Added `'Video'` to the `collections` aray in `views/admin/index.js`. This causes a JS error: `TypeError: Cannot read property 'count' of undefined` on line 10 of the same file (because `'Video'` is undefined; I don't know how to make it defined).

3. Created a `Video.js` file in `/schema/`, again copied from `Status.js` and all "Status" changed to "Video".

I'd like to solve the errors posted in 1. and 2.; I've already done `use drywall; db.createCollection("Video")` in the Mongo terminal to no avail. Thank you in advance! :)

**Comment by jedireza** [comment]
Thanks for opening an issue. The css/js are breaking because you need to create versions for your new `videos` section. These are found in the `/public` folders.
