### ISSUE TITLE
Use Admin Notes Feature as Basis of Activity/Newsfeed?

### ISSUE THREAD

**Issue by atonb117** [jedireza/drywall#397]
I'm playing around with the notes form on the Admin Accounts route.

If I want to incorporate a social media type activity or news feed, would it be more efficient to reuse and build out the existing note feature or create something new from scratch?

I dont expect any major real-time needs, just the ability for users to post and read notes (with additional meta data like data) to other user's profiles.

**Comment by jedireza** [comment]
Thanks for opening an issue.

> If I want to incorporate a social media type activity or news feed, would it be more efficient to reuse and build out the existing note feature or create something new from scratch?

It's hard to answer your question definitively since I don't know more about the goals. I suggest doing what you feel is best and adapt things as necessary.
