### ISSUE TITLE
Public Profile and Group Pages

### ISSUE THREAD

**Issue by atonb117** [jedireza/drywall#398]
I'm experimenting with creating a route that presents a user's profile info to other users.  Not anticipating any problems with that.

However, I'm reading and rereading the [Users, Roles & Groups](https://github.com/jedireza/drywall/wiki/Users,-Roles-&-Groups) wiki and I'm trying to get an idea of how to allow users with appropriate permissions to create a group, add users to group, while allowing other users join group (if they have permissions to set it).

Key to this is the group has it's own public (or private) page/route displaying group info and allowing group members (with appropriate permissions) to post notes ( #397 ) to the group.

Any advice or direction would be great!

Thanks!

**Comment by jedireza** [comment]
Thanks for opening an issue.

First, there are no rules 😁. The system as it is, was designed with the idea that admins and groups would be like a company of people (admins) and their departments (admin groups). Typically you'd have select people who manage ("assign") other people's permissions and groups, which is different than letting users "join".

You can use it in a different way, but you'd need to customize things to fit your needs. My advice is to get comfortable with the modules/tech that Drywall is built with and customize as you see fit.

Also, checkout [Frame](https://github.com/jedireza/frame/). It's the essentially the API part of Drywall, with better test coverage and without a front-end.
