### ISSUE TITLE
Can't access admin area - Redirected to the home page

### ISSUE THREAD

**Issue by OmarTrigui** [jedireza/drywall#399]
I'm hosting drywall on my localhost. After a successful request for renewing the password and logging in, i was unable to access the admin area ( Clicking on my username in the top right corner )

Why i can't get my saved collections ?

**Comment by jedireza** [comment]
Thanks for opening an issue.

> I'm hosting drywall on my localhost. After a successful request for renewing the password and logging in, i was unable to access the admin area ( Clicking on my username in the top right corner )

That sounds like you logged in with an Account role, not an Admin role. Did you follow the instructions on the README under the "setup" heading?

> Why i can't get my saved collections ?

I'm not sure what you mean by this.

**Comment by jedireza** [comment]
Drywall has been moved to Aqua. Closing this issue.
