### ISSUE TITLE
Where are the log files ..?

### ISSUE THREAD

**Issue by nagarjunbn8** [jedireza/drywall#402]
I am not able to find the error and console log in the package.. where are those located.? How can I create one .?

**Comment by scottmont** [comment]
use grunt it will show the log in the console.

**Comment by jedireza** [comment]
Thanks for opening an issue @nagarjunbn8. Did @scottmont's answer help?

**Comment by nagarjunbn8** [comment]
Yes .Thanks for the answer @scottmont . But how can I dump those to a file for tracking errors in the production server.

**Comment by jedireza** [comment]
We don't store log files by default. Usually that's handled by you or your hosting environment.

For example, Heroku allows you to see logs via `$ heroku logs`.

 - https://devcenter.heroku.com/articles/logging
 - http://stackoverflow.com/questions/2671454/heroku-how-to-see-all-the-logs
