### ISSUE TITLE
How can i display (account/settings) data in account home page

### ISSUE THREAD

**Issue by Ingeskhaled** [jedireza/drywall#404]
Hi,

As i'm new using Node.js, i would like to know how can i display data (First Name, Last Name, Phone and so) from settings home page into account home page after updating. I did it for the registration information (username and email) using 

```
`app.use(function(req, res, next) {`
`  res.cookie('_csrfToken', req.csrfToken());`
  res.locals.user = {};
  res.locals.user.defaultReturnUrl = req.user && req.user.defaultReturnUrl();
  res.locals.user.username = req.user && req.user.username;
  res.locals.user.email = req.user && req.user.email;
  next();
});

``
```

Many thanks in advance !!

**Comment by jedireza** [comment]
Thanks for opening an issue. Sorry about the delayed response.

That's one way to do it, but it's probably best to query the database for what you need on the pages you need it.
