### ISSUE TITLE
No CSS files

### ISSUE THREAD

**Issue by SamuelzXu** [jedireza/drywall#405]
Where are all the css files? I cannot find them anywhere in the directory and my console returns 404 for all the css files. Was I not correct in thinking that this template would also provide the css files? Either way, this project is amazing. I saw the live demo on heroku and that looked gorgeous, but the one I ran on localhost was just a barebones html file due to the lack of css files. Thanks!

**Comment by sc0Vu** [comment]
Maybe they will copy after you use grunt command.

See: https://github.com/gruntjs/grunt-contrib-copy

**Comment by jedireza** [comment]
Thanks for opening an issue. And yes you should use `grunt` to generate the client-side files.
