### ISSUE TITLE
how to set this via node init.js?

### ISSUE THREAD

**Issue by suriyaJaay** [jedireza/drywall#407]
just tried to give input for init.js  as below but it throws some error

F:\2nd Version - Angular - Examples\Angular_DRY WALL__\angular-drywall-master>node init.js
=====Create admin user=====
username (root) jsuriya
email hi.jayasurya@gmail.com
password
=====Setup Mongo DB=====
MongoDB host (localhost) drywall
MongoDB port (27017)
MongoDB database (angular-drywall) Suriya-drywall
MongoDB user Jsuriya
MongoDB password
=====(Optional) Set smtp server credential (to send notification email)=====
smtp username (hi.jayasurya@gmail.com) Jsuriya
smtp password
smtp server host (smtp.gmail.com) suriyaJaay
error connecting to db, please verify Mongodb setting then try again.

F:\2nd Version - Angular - Examples\Angular_DRY WALL__\angular-drywall-master>

before that did start mongo

**Comment by jedireza** [comment]
You're probably using a different project (one forked from Drywall maybe). We never used Angular in Drywall.
